<!--
    This template file is for the account settings.
    File acts as a view file for our Account.
-->

<?php
// initialize all values required on this page
$existingRules = $this->get_existingRules();
$existingRules_customer = $this->get_customerexistingRules();

print_r('      <div class="row">
<div class="">
            <div class="page" id="account" style="">
            <div class="mosp_table_layout">');

if ($existingRules || $existingRules_customer) {
    echo $this->getLayout()
        ->createBlock("MiniOrange\TwoFA\Block\TwoFA")
        ->setTemplate("MiniOrange_TwoFA::2fa_settings_configuration_table.phtml")
        ->toHtml();
} else {
    echo $this->getLayout()
        ->createBlock("MiniOrange\TwoFA\Block\TwoFA")
        ->setTemplate("MiniOrange_TwoFA::2fa_admin_customer_box.phtml")
        ->toHtml();
}


print_r('       </div>
        </div>');
