<style>

    .bg-white {
        --tw-bg-opacity: 1;
        background-color: rgb(255 255 255 / var(--tw-bg-opacity));
    }

    .mo-content-wrapper {
        display: flex;
        gap: 1.5rem;
        padding: 2rem;
    }

    .gap-mo-32 {
        gap: 8rem;
    }

    .gap-mo-32 {
        gap: 8rem;
    }

    .flex {
        display: flex;
    }

    .inline-flex {
        display: inline-flex;
    }


    .gap-mo-4 {
        gap: 1rem;
    }

    .px-mo-32 {
        padding-left: 8rem;
        padding-right: 8rem;
    }

    .cursor-pointer {
        cursor: pointer;
    }

    .flex-row {
        flex-direction: row;
    }

    .flex-col {
        flex-direction: column;
    }

    .items-center {
        align-items: center;
    }

    .justify-end {
        justify-content: flex-end;
    }

    .justify-center {
        justify-content: center;
    }

    .w-full {
        width: 100%;
    }

    .mo-input-wrapper {
        position: relative;
        width: 100%;
    }


    .mo-input-label {
        font-weight: 500;
        border-radius: 4px;
        position: absolute;
        top: -0.625rem;
        left: 0.75rem;
        --tw-bg-opacity: 1;
        background-color: rgb(255 255 255 / var(--tw-bg-opacity));
        padding-left: 0.5rem;
        padding-right: 0.5rem;
        font-size: 12px;
        --tw-text-opacity: 1;
        color: rgb(100 116 139 / var(--tw-text-opacity));
    }

    .mo-textarea,
    .mo-input[type='text'],
    .mo-input[type='password'],
    .mo-input[type='textarea'],
    .mo-input[type='url'],
    .mo-input[type='email'] {
        -webkit-appearance: none;
        outline: none !important;
        box-shadow: none !important;
        border: 2px solid;
        border-radius: 0.375rem;
        --tw-border-opacity: 1;
        border-color: rgb(226 232 240 / var(--tw-border-opacity));
        padding-left: 1rem;
        padding-right: 1rem;
        padding-top: 0.75rem;
        padding-bottom: 0.75rem;
        transition-duration: 200ms;
    }

    .mo-textarea:disabled,
    .mo-input[type='text']:disabled,
    .mo-input[type='password']:disabled,
    .mo-input[type='textarea']:disabled,
    .mo-input[type='url']:disabled,
    .mo-input[type='email']:disabled {
        cursor: not-allowed;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    .mo-textarea:focus,
    .mo-input[type='text']:focus,
    .mo-input[type='password']:focus,
    .mo-input[type='textarea']:focus,
    .mo-input[type='url']:focus,
    .mo-input[type='email']:focus {
        outline: none !important;
        box-shadow: none !important;
        border: 2px solid black;
        --tw-border-opacity: 1;
        border-color: #eb5202;
    }

    .mo-input-label {
        font-weight: 500;
        border-radius: 4px;
        position: absolute;
        top: -0.625rem;
        left: 0.75rem;
        --tw-bg-opacity: 1;
        background-color: rgb(255 255 255 / var(--tw-bg-opacity));
        padding-left: 0.5rem;
        padding-right: 0.5rem;
        font-size: 12px;
        --tw-text-opacity: 1;
        color: rgb(100 116 139 / var(--tw-text-opacity));
    }

    .group:focus-within .mo-input-label {
        font-weight: 700;
        --tw-text-opacity: 1;
        color: #eb5202;
    }


    /*
        Button Styles
    */

    .mo-button {
        display: flex;
        height: 40px;
        width: 100%;
        cursor: pointer;
        flex-direction: row;
        align-items: center;
        justify-content: center;
        gap: 0.75rem;
        border-radius: 0.375rem;
        border-style: none;
        padding-left: 1.5rem;
        padding-right: 1.5rem;
        text-align: center;
        font-size: 14px;
        font-weight: 700;
        text-decoration-line: none;
    }

    .mo-button:hover {
        text-decoration-line: none !important;
    }

    .mo-button:disabled {
        --tw-bg-opacity: 1;
        background-color: rgb(199 210 254 / var(--tw-bg-opacity));
    }

    @media (min-width: 640px) {
        .mo-button {
            width: auto;
        }
    }

    .mo-button.medium {
        display: flex;
        height: 35px;
        width: 100%;
        cursor: pointer;
        flex-direction: row;
        align-items: center;
        justify-content: center;
        gap: 0.75rem;
        border-radius: 0.375rem;
        border-style: none;
        padding-left: 1rem;
        padding-right: 1rem;
        text-align: center;
        font-size: 12px;
        font-weight: 700;
        text-decoration-line: none;
    }

    .mo-button.medium:hover {
        text-decoration-line: none;
    }

    @media (min-width: 640px) {
        .mo-button.medium {
            width: auto;
        }
    }

    .mo-button.primary {
        --tw-bg-opacity: 1;
        background-color: rgb(99 102 241 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(255 255 255 / var(--tw-text-opacity));
    }

    .mo-button.primary:hover {
        --tw-bg-opacity: 1;
        background-color: rgb(79 70 229 / var(--tw-bg-opacity));
    }

    .mo-button.primary:disabled {
        cursor: not-allowed;
        --tw-bg-opacity: 1;
        background-color: rgb(199 210 254 / var(--tw-bg-opacity));
    }

    .mo-button.secondary {
        border: 1px solid rgb(203 213 225);
        --tw-bg-opacity: 1;
        background-color: rgb(255 255 255 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(0 0 0 / var(--tw-text-opacity));
        gap: .75rem;
        border-radius: .375rem;
        /* border-style: none; */
        text-align: center;
        display: flex;
        cursor: pointer;
    }

    .mo-button.secondary:hover {
        background-color: rgb(241 245 249);
        color: rgb(0 0 0 / var(--tw-text-opacity));
        border: 1px solid rgb(203 213 225);
    }

    .mo-button.secondary:disabled {
        cursor: not-allowed;
        --tw-bg-opacity: 1;
        background-color: rgb(248 250 252 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(156 163 175 / var(--tw-text-opacity));
    }

    .mo-button.inverted {
        border-width: 1px;
        --tw-bg-opacity: 1;
        background-color: rgb(0 0 0 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(255 255 255 / var(--tw-text-opacity));
    }

    .mo-button.inverted:hover {
        --tw-bg-opacity: 1;
        background-color: rgb(15 23 42 / var(--tw-bg-opacity));
    }

    .mo-button.inverted:disabled {
        cursor: not-allowed;
        --tw-bg-opacity: 1;
        background-color: rgb(75 85 99 / var(--tw-bg-opacity));
    }

    .mo-button.alert {
        border-width: 1px;
        --tw-bg-opacity: 1;
        background-color: rgb(239 68 68 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(255 255 255 / var(--tw-text-opacity));
    }

    .mo-button.recharge {
        border: 1px solid rgb(203 213 225);
        height: 34px;
        border-radius: 0.25rem;
        --tw-bg-opacity: 1;
        background-color: rgb(255 255 255 / var(--tw-bg-opacity));
        padding-left: 1rem;
        padding-right: 1rem;
        font-size: 0.75rem;
        line-height: 1rem;
        --tw-text-opacity: 1;
        color: rgb(0 0 0 / var(--tw-text-opacity));
    }

    .mo-button.recharge:hover {
        --tw-bg-opacity: 1;
        background-color: rgb(241 245 249 / var(--tw-bg-opacity));
    }

    .mo-button.blue {
        --tw-bg-opacity: 1;
        background-color: rgb(29 78 216 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(255 255 255 / var(--tw-text-opacity));
    }

    .mo-button.secondary {
        border: 1px solid rgb(203 213 225);
        --tw-bg-opacity: 1;
        background-color: rgb(255 255 255 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(0 0 0 / var(--tw-text-opacity));
    }

    .mo-button.secondary:hover {
        /* --tw-bg-opacity: 1;
        background-color: rgb(241 245 249 / var(--tw-bg-opacity)); */
    }

    .mo-button.secondary:disabled {
        cursor: not-allowed;
        --tw-bg-opacity: 1;
        background-color: rgb(248 250 252 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(156 163 175 / var(--tw-text-opacity));
    }

    .mo-form-button.secondary {
        border: 1px solid rgb(203 213 225);
        height: 30px;
        width: 30px;
        cursor: pointer;
        align-items: center;
        justify-content: center;
        border-radius: 0.375rem;
        --tw-bg-opacity: 1;
        background-color: rgb(255 255 255 / var(--tw-bg-opacity));
        text-align: center;
        font-size: 14px;
        font-weight: 700;
        --tw-text-opacity: 1;
        color: rgb(0 0 0 / var(--tw-text-opacity));
    }

    .mo-form-button.secondary:hover {
        /* --tw-bg-opacity: 1;
        background-color: rgb(241 245 249 / var(--tw-bg-opacity)); */
    }

    .mo-button.secondary:hover {
        /* --tw-bg-opacity: 1;
        background-color: rgb(241 245 249 / var(--tw-bg-opacity)); */
    }

    .mo-button.secondary:disabled {
        cursor: not-allowed;
        --tw-bg-opacity: 1;
        background-color: rgb(248 250 252 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(156 163 175 / var(--tw-text-opacity));
    }

    .mo-form-button.secondary {
        border: 1px solid rgb(203 213 225);
        height: 30px;
        width: 30px;
        cursor: pointer;
        align-items: center;
        justify-content: center;
        border-radius: 0.375rem;
        --tw-bg-opacity: 1;
        background-color: rgb(255 255 255 / var(--tw-bg-opacity));
        text-align: center;
        font-size: 14px;
        font-weight: 700;
        --tw-text-opacity: 1;
        color: rgb(0 0 0 / var(--tw-text-opacity));
    }

    .mo-form-button.secondary:hover {
        --tw-bg-opacity: 1;
        background-color: rgb(241 245 249 / var(--tw-bg-opacity));
    }

    .rounded-xl {
        border-radius: 0.75rem;
    }

    .mo-heading {
        font-size: 16px;
        font-weight: 600;
        line-height: 1.5;
    }

    .text-lg {
        font-size: 1.125rem;
        line-height: 1.75rem;
    }

    .mt-mo-2\.5 {
        margin-top: 0.625rem;
    }

    .mt-mo-2 {
        margin-top: 0.5rem;
    }

    .py-mo-4 {
        padding-top: 1rem;
        padding-bottom: 1rem;
    }

    .second {

        border: 1px solid black;
        --tw-bg-opacity: 1;
        background-color: rgb(255 255 255 / var(--tw-bg-opacity));
        --tw-text-opacity: 1;
        color: rgb(0 0 0 / var(--tw-text-opacity));
        gap: .75rem;
        border-radius: .375rem;
        /* border-style: none; */
        text-align: center;
        display: flex;
        cursor: pointer;
        border: 1px solid rgb(203 213 225);
    }

    .text-3xl {
        font-size: 1.875rem;
    }

    .font-bold {
        font-weight: 700;
    }

    .mb-6 {
        margin-bottom: 1.5rem;
    }

    .text-gray-900 {
        color: #4a5568;
    }

    .p-8 {
        padding: 2rem;
    }

    .py-4 {
        padding-top: 1rem;
        padding-bottom: 1rem;
    }

    .pl-8 {
        padding-left: 2rem;
    }

    .mo-input-wrapper {
        position: relative;
        width: 100%;
    }

    button:hover {
        background-color: #dbdbdb;
        color: #514943;
        border: none;
    }


</style>
<?php
/**
 * Loads View for verifying license key in Magento.
 */

// Escape the necessary URLs and form key
$url = $this->escapeUrl($this->getMiniOrangeUrl() . '/moas/login?redirectUrl=' . $this->getMiniOrangeUrl() . '/moas/viewlicensekeys');
$formKey = $this->getBlockHtml('formkey');
    $email = $this->getCustomerEmail();
?>

<div class="p-8" style="width:70%;">
    <div class="px-mo-32">

        <div class="justify-center items-center">
            <div class="bg-white rounded-xl flex flex-col gap-mo-4">
                <div class="flex" style="justify-content:space-between;">
                    <h1 class="text-3xl font-bold mb-6 text-gray-900 my-4"
                        style="font-size: 2.5rem; display: block;color:black">
                        Verify Your License
                    </h1>
                    <span class="flex">
                        <form name="goBackForm" method="post" action="">
                            <?php echo $formKey; ?>
                            <input type="hidden" name="option" value="removeAccount" >
                            <button class="second mo-button" onclick="goBack()" id="remove_plugin">
                                <?php echo htmlspecialchars(__('Go Back')); ?>
                            </button>
                        </form>
                    </span>
                </div>
                <p>
                    <a class="font-semibold text-blue-500" href="<?php echo $url; ?>"
                       target="_blank">[<?php echo htmlspecialchars(__('  Click here to view your license key  ')); ?>
                        ]
                    </a>
                </p>
                <form name="f" method="post" action="">
                    <?php echo $formKey; ?>
                    <input type="hidden" name="option" value="verifyLicenseKey" >
                    <div class="py-mo-4">
                        <div class="w-full mo-input-wrapper group">
                            <label class="mo-input-label"><?php echo htmlspecialchars(__('miniOrange Account Email')); ?></label>
                            <input class="w-full mo-input" type="text" name="lk" style="height: 5rem;"
                                   value=<?php echo $email; ?> readonly >
                        </div>
                    </div>
                    <div class="py-mo-4">
                        <div class="w-full mo-input-wrapper group">
                            <label class="mo-input-label"><?php echo htmlspecialchars(__('License Key')); ?></label>
                            <input class="w-full mo-input" type="text" name="lk" style="height: 5rem;"
                                   placeholder="<?php echo htmlspecialchars(__('Enter your license key to activate the plugin')); ?>"
                                   value="" >
                        </div>
                    </div>
                    <div class="py-4 pl-8">
                        <b>Please read and accept the following before activating your license key :</b>
                        <div
                            style="border-left: solid 2px rgba(128, 128, 128, 0.65);margin-top: 10px;padding-left: 10px;">
                            <div style="float:left;height:50px;margin-right:5px;"><input type="checkbox" required
                                                                                         id="lk_check1"
                                                                                         value="1" required></div>
                            <div><b><i>License key you have entered here is associated with this site instance.</i></b>
                                If you want to re-install the plugin for any reason, you should deactivate and then
                                delete the plugin from Magento console. Manually deleting the plugin folder will not
                                free your key for re-use.
                            </div>
                            <br>
                            <div style="float:left;height:50px;margin-right:5px;"><input type="checkbox" required
                                    id="lk_check2" value="1" required></div>
                            <div><b><i>This is not a developer license.</i></b> Making any kind of change to the
                                plugin\'s code will delete all your configuration and make the plugin unusable.
                            </div>
                        </div>

                    </div>
                    <div class="py-mo-4 my-4">
                        <input type="submit" name="submit" style="background-color:#eb5202" id="activate_plugin" value="<?php echo htmlspecialchars(__('Activate License')); ?>"
                            class="mo-button inverted">
                    </div>
                </form>
                <form name="f" method="post" action="">
                    <?php echo $formKey; ?>
                    <input type="hidden" name="option" value="skipAndStartTrial" />
                    <input type="submit" style="float:left; margin-left:4cm; height:40px; margin-top:-70px" name="submit" id="remove_plugin" class="btn-round" value="Skip & Keep Trial Active"/>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            $('a[href="#goToLoginPage"]').click(function (e) {
                e.preventDefault();
                $("#goToLoginPageForm").submit();
            });

            // Enable submit button when both checkboxes are checked
            $('#lk_check1, #lk_check2').on('change', function () {
                const isChecked = $('#lk_check1').is(':checked') && $('#lk_check2').is(':checked');
                $('#activate_plugin').prop('disabled', !isChecked);
            });
        });
    });

    function goBack() {
        document.goBackForm.submit(); // Submit the form explicitly
    }

</script>
