<?php

$formKey = $this->getBlockHtml('formkey');
$request = $this->getRequestVariable();
$email = $this->getSessionUsername();


if (!$email) {
    // Get the base URL (homepage)
    $this->emailerror();
    $redirectUrl = $this->getBaseUrl();
    echo "<script type='text/javascript'>window.location.href = '$redirectUrl';</script>";
    return;
}

$customer_role = $this->getCurrentCustomerRole($email);
if (!$customer_role) {
    // Get the base URL (homepage)
    $this->emailerror();
    $redirectUrl = $this->getBaseUrl();
    echo "<script type='text/javascript'>window.location.href = '$redirectUrl';</script>";
    return;
}

$current_website_id = $this->get_customer_current_websiteID();
$twofaMethods = $this->getCustomer2FAMethodsFromRules($customer_role, $current_website_id, $email);
$activeMethods = json_decode($twofaMethods['methods'], true);
$active_method_number = $twofaMethods['count'];

// If user has multiple methods but has configured a specific method, use only that method
if ($active_method_number > 1 && !empty($email)) {
    $userDetails = $this->getUserDetailsforcustomerreset();
    if (!empty($userDetails) && isset($userDetails[0]['active_method']) && !empty($userDetails[0]['active_method'])) {
        $userActiveMethod = $userDetails[0]['active_method'];
        $activeMethods = [$userActiveMethod];
        $active_method_number = 1;
    }
}

// Handle case when active methods are not available or empty
if (is_null($activeMethods) || empty($activeMethods)) {
    $activeMethods = ['OOE']; // Default to OTP Over Email
    $active_method_number = 1;
}

$formPostUrl = $this->getBaseUrl() . "motwofa/mocustomer";
$loginPageUrl = $this->getBaseUrl() . "customer/account/login/";
$error = isset($request['error']);

$show_kba_button = $this->show_kba_button($current_website_id);
$popup_ui_values = $this->getPopupUI_values() ? $this->getPopupUI_values() : '';


$customer_skip_twofa = (int)$this->do_customer_skip_twofa();

$is_device_based_enabled = $this->get_customer_remember_device();
$redirectUrl = $this->getBaseUrl();

$is_device_limit_exceeded = $this->is_device_limit_exceeded($current_website_id, $email);


if (isset($request['mooption'])) {
    if ("invokeTFA" == $request['mooption']) {
        $method = isset($request['active_method']) ? $request['active_method'] : NULL;
        
        // Initialize OTP length with default value
        $otp_length = 6; 
        
        if ($method && ($method == 'MicrosoftAuthenticator' || $method == 'GoogleAuthenticator')) {
            $otp_length = 6;
        } else if ($method) {
            // Use OTP length setting for non-authenticator methods
            $otp_length = $this->getOtpLengthForMethod($method);
        } else {
            // If no method is specified, try to determine from URL parameters or default to OOE for email-based OTP
            $step = isset($request['step']) ? $request['step'] : '';
            if ($step === 'OOSMethodValidation') {
                $method = 'OOS';
            } else if ($step === 'OOEMethodValidation') {
                $method = 'OOE';
            } else if ($step === 'OOSEMethodValidation') {
                $method = 'OOSE';
            } else {
                // Default to OOE for email-based OTP if no other method is specified
                $method = 'OOE';
            }
            $otp_length = $this->getOtpLengthForMethod($method);
        }
        
        // help button: send mail to admin email
        $adminEmail = $this->getAdminEmail();
        InvokeUserTFA($formKey, $formPostUrl, $loginPageUrl, $error, $request, $show_kba_button, $popup_ui_values, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length, $adminEmail);
    } else if ("invokeInline" == $request['mooption'] && isset($request['step'])) {

        switch ($request['step']) {

            case "ChooseMFAMethod":
                $tfaArray = $this->getAllTfaMethods();
                ChooseMFAMethod($formKey, $activeMethods, $tfaArray, $formPostUrl, $loginPageUrl, $popup_ui_values, $customer_skip_twofa);
                break;
            case "OOSMethodValidation":
                $otp_length = $this->getOtpLengthForMethod('OOS');
                OOSMethodValidation($formKey, $formPostUrl, $error, $request, $active_method_number, $loginPageUrl, $popup_ui_values, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length);
                break;
            case "OOWMethodValidation":
                $otp_length = $this->getOtpLengthForMethod('OOW');
                OOWMethodValidation($formKey, $formPostUrl, $error, $request, $active_method_number, $loginPageUrl, $popup_ui_values, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length);
                break;
            case "GAMethodValidation":
                $otp_length = 6;
                $issuer = $this->AuthenticatorIssuer();
                $QrcodeJS = $this->getQrCodeJS();
                $AuthUrl = $this->AuthenticatorCustomerUrl($email);
                $secret = $this->getCustomerSecret();
                GAMethodValidation($formKey, $formPostUrl, $AuthUrl, $issuer, $QrcodeJS, $error, $active_method_number, $loginPageUrl, $popup_ui_values, $secret, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $request, $otp_length);
                break;
            case "AMethodValidation":
                $otp_length = 6; 
                $issuer = $this->AuthenticatorIssuer();
                $QrcodeJS = $this->getQrCodeJS();
                $AuthUrl = $this->AuthenticatorCustomerUrl($email);
                $secret = $this->getCustomerSecret();
                AMethodValidation($formKey, $formPostUrl, $AuthUrl, $issuer, $QrcodeJS, $error, $active_method_number, $loginPageUrl, $popup_ui_values, $secret, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $request, $otp_length);
                break;
            case "MicrosoftAuthenticator":
                $otp_length = 6;
                $issuer = $this->AuthenticatorIssuer();
                $QrcodeJS = $this->getQrCodeJS();
                $AuthUrl = $this->AuthenticatorCustomerUrl($email);
                $secret = $this->getCustomerSecret();
                MicrosoftAuthMethodValidation($formKey, $formPostUrl, $AuthUrl, $issuer, $QrcodeJS, $error, $active_method_number, $loginPageUrl, $popup_ui_values, $secret, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $request, $otp_length);
                break;
            case "OOEMethodValidation":
                $otp_length = $this->getOtpLengthForMethod('OOE');
                OOEMethodValidation($formKey, $formPostUrl, $error, $request, $active_method_number, $loginPageUrl, $popup_ui_values, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length);
                break;
            case "OOSEMethodValidation":
                $otp_length = $this->getOtpLengthForMethod('OOSE');

                OOSEMethodValidation($formKey, $formPostUrl, $error, $request, $active_method_number, $loginPageUrl, $popup_ui_values, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length, $redirectUrl);
                break;
            case "KBA_Question":
                $KBAQuestion_set1 = $this->KBAQuestion_set1($current_website_id);
                $KBAQuestion_set2 = $this->KBAQuestion_set2($current_website_id);
                KBAMethod($formKey, $formPostUrl, $loginPageUrl, $KBAQuestion_set1, $KBAQuestion_set2, $popup_ui_values, $is_device_based_enabled, $is_device_limit_exceeded);
                break;
            case "KBA_Validate":
                $kba_random_questions = $this->get_kba_question();
                KBAValidate($formKey, $formPostUrl, $loginPageUrl, $kba_random_questions, $popup_ui_values, $is_device_based_enabled, $is_device_limit_exceeded);
                break;
            default:
                InvalidRequest();
        }
    } else {
        InvalidRequest();
    }

} else {
    InvalidRequest();
}

function OOSMethodValidation($formKey, $formPostUrl, $error, $request, $active_method_number, $loginPageUrl, $popup_ui_values, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length)
{
    ?>
    <body style="background-size: 100% 100%; background-color: <?php if (isset($popup_ui_values->BgColor)) {
        echo $popup_ui_values->BgColor;
    } else {
        echo "white";
    }
    ?>">
    <div class="customer_card container_new" style="background-color: <?php
    if (isset($popup_ui_values->popupBgColor)) {
        echo $popup_ui_values->popupBgColor;
    } else {
        echo "white";
    }
    ?>">
        <br>

        <div class="card-description">
            <!-- Phone Input Form -->
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <input type="hidden" name="mopostoption" value="challenge">
                <input type="hidden" id="redirect_to" name="redirect_to" value="">
                <div style="<?php echo isset($request['showdiv']) ? 'display: none;' : 'display: block;'; ?>">
                    <div class="top_icon">
                        <div class="back-button">
                            <?php if ($active_method_number == 1) { ?>
                                <!-- If active method number is 1, link to the login page -->
                                <a href="<?php echo $loginPageUrl; ?>" class="back-button"
                                   style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                       echo $popup_ui_values->popupBtnColor;
                                   } else {
                                       echo "#ff8500";
                                   } ?>">← Back</a>
                            <?php } else { ?>
                                <!-- Otherwise, call the previousStep function -->
                                <a href="#" class="back-button"
                                   style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                       echo $popup_ui_values->popupBtnColor;
                                   } else {
                                       echo "#ff8500";
                                   } ?>" onclick="previousStep()">← Back</a>
                            <?php } ?>
                        </div>

                    </div>
                    <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                        echo $popup_ui_values->popupTextColor;
                    } else {
                        echo "black";
                    } ?>">Two-Factor Authentication</h2>
                    <p>To secure your account, please provide your phone number for two-factor authentication.</p>
                    <br><br>
                    <div class="phone-input-container">
                        <!-- Country Code Dropdown -->
                        <?php countrycode($popup_ui_values); ?>

                        <!-- Phone Number Input -->
                        <input type="number" class="phone-number-input" placeholder="Enter your number" name="phone"
                               required/>
                    </div>
                    <br>
                    <button type="submit" class="btn-primary"
                            style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>" style="">Send OTP
                    </button>
                </div>
            </form>

            <!-- Passcode Verification Form -->
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <input type="hidden" name="mopostoption" value="movalotp">
                <input type="hidden" name="savestep" value="OOS">
                <input type="hidden" id="Passcode" name="Passcode">

                <div style="<?php echo isset($request['showdiv']) ? 'display: block;' : 'display: none;'; ?>">
                    <input type="hidden" name="phone" value="<?php echo htmlspecialchars($request['phone'] ?? ''); ?>">
                    <input type="hidden" name="countrycode"
                           value="<?php echo htmlspecialchars($request['countrycode'] ?? ''); ?>">

                    <div class="container_new" style="background-color: <?php
                    if (isset($popup_ui_values->popupBgColor)) {
                        echo $popup_ui_values->popupBgColor;
                    } else {
                        echo "white";
                    }
                    ?>">
                        <div class="top_icon">
                            <div class="back-button"
                                 style="color: <?php echo isset($popup_ui_values->popupBtnColor) ? $popup_ui_values->popupBtnColor : '#ff8500'; ?>;">
                                <?php if ($active_method_number == 1) { ?>
                                    <!-- If active method number is 1, link to the login page -->
                                    <a href="<?php echo $loginPageUrl; ?>" class="back-button"
                                       style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                           echo $popup_ui_values->popupBtnColor;
                                       } else {
                                           echo "#ff8500";
                                       } ?>">← Back</a>
                                <?php } else { ?>
                                    <!-- Otherwise, call the previousStep function -->
                                    <!-- if else if otp alreadt present -->
                                    <a href="#" class="back-button"
                                       style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                           echo $popup_ui_values->popupBtnColor;
                                       } else {
                                           echo "#ff8500";
                                       } ?>"
                                       onclick="previousStep()">← Back</a>
                                <?php } ?>
                            </div>

                        </div>
                        <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                            echo $popup_ui_values->popupTextColor;
                        } else {
                            echo "black";
                        } ?>">Two-Factor Authentication</h2>
                        <div class="message_container"
                             style="color: <?php echo $error ? '#721c24' : '#155724'; ?>; background-color:
                             <?php echo $error ? '#f8d7da' : '#d4edda'; ?>; border: 0.1rem solid <?php echo $error ? '#f5c6cb' : '#c3e6cb'; ?>;">
                            <?php if (isset($request['message']) && !$error): ?>
                                <?php echo $request['message']; ?>
                            <?php elseif ($error): ?>
                                <?php showerrormessage($popup_ui_values); ?>
                            <?php endif; ?>
                        </div>

                        <div class="input-group" id="moPass">
                            <?php for ($i = 1; $i <= $otp_length; $i++): ?>
                                <input type="text" maxlength="1" inputmode="numeric"
                                       aria-label="Verification Code Digit <?php echo $i; ?>">
                            <?php endfor; ?>
                        </div>

                        <!-- rememvber my device -->
                        <?php if ($is_device_based_enabled && $is_device_limit_exceeded): ?>
                            <div class="customer_row" style="margin-top: 15px; margin-bottom: 10px;">
                                <div class="col-sm-12">
                                    <input type="checkbox" id="rememberDevice" name="rememberDevice" value="1"
                                           style="margin-right: 10px;">
                                    <label for="rememberDevice">Remember My Device</label>
                                </div>
                            </div>
                        <?php endif; ?>
                        <br>
                        <button class="btn-primary"
                                style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                    echo $popup_ui_values->popupBtnColor;
                                } else {
                                    echo "#ff8500";
                                } ?>">Verify
                        </button>
            </form>

            <div class="secondary-actions"
                 style="display: flex; margin-top: 20px; align-content: center; justify-content: space-between; align-items: center;">
                <?php if ($customer_skip_twofa == 1) { ?>
                    <?php echo $formKey; ?>
                    <div class="skipTwoFa_section">
                        <form method="post" name="skip-twoFA-remind" action="<?php echo $formPostUrl; ?>">
                            <?php echo $formKey; ?>
                            <input type="hidden" name="skiptwofa" value="skip_twofa">
                            <!-- Replace the button with a link -->
                            <button class="skip_button" style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>" type="submit">Remind Me Later
                            </button>
                        </form>
                    </div>
                <?php } ?>
                <a href="#" style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                    echo $popup_ui_values->popupBtnColor;
                } else {
                    echo "#ff8500";
                } ?>" class="resend-link">Resend Code</a>
            </div>
        </div>
    </div>
    </div>

    <script>

        // Navigation functions
        function OOS_previousStep() {
            window.location.href = "?mooption=invokeInline&step=OOSMethodValidation&savestep=OOS";
        }

        function previousStep() {
            window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
        }

        function SMS_previousStep() {
            window.location.href = "?mooption=invokeInline&step=OOSMethodValidation&savestep=OOS";
        }

        function redirectToLoginPage() {
            const loginPageUrl = "<?php echo $loginPageUrl; ?>";
            window.location.href = loginPageUrl;
        }

        // Set the redirect_to input value to the current page URL
        window.onload = function () {
            const redirectToInput = document.getElementById("redirect_to");
            if (redirectToInput) {
                redirectToInput.value = window.location;
            }
        };
    </script>

    </div>
    </body>
    <?php
}

function OOWMethodValidation($formKey, $formPostUrl, $error, $request, $active_method_number, $loginPageUrl, $popup_ui_values, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length)
{
    ?>
    <body style="background-size: 100% 100%; background-color: <?php if (isset($popup_ui_values->BgColor)) {
        echo $popup_ui_values->BgColor;
    } else {
        echo "white";
    }
    ?>">

    <!-- Customer Card Container -->
    <div class="customer_card container_new" style="background-color: <?php
    if (isset($popup_ui_values->popupBgColor)) {
        echo $popup_ui_values->popupBgColor;
    } else {
        echo "white";
    }
    ?>">
        <br>

        <div class="card-description">
            <!-- Phone Input Form-1 -->
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <input type="hidden" name="mopostoption" value="challenge">
                <input type="hidden" id="redirect_to" name="redirect_to" value="">

                <!-- Display the phone input form if no previous step -->
                <div style="<?php echo isset($request['showdiv']) ? 'display: none;' : 'display: block;'; ?>">
                    <div class="top_icon">
                        <div class="back-button">
                            <!-- If active method is 1, provide a link to login page, else use back functionality -->
                            <?php if ($active_method_number == 1) { ?>
                                <a href="<?php echo $loginPageUrl; ?>" class="back-button"
                                   style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                       echo $popup_ui_values->popupBtnColor;
                                   } else {
                                       echo "#ff8500";
                                   } ?>">← Back</a>
                            <?php } else { ?>
                                <a href="#" class="back-button"
                                   style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                       echo $popup_ui_values->popupBtnColor;
                                   } else {
                                       echo "#ff8500";
                                   } ?>" onclick="previousStep()">← Back</a>
                            <?php } ?>
                        </div>
                        <!-- Help link -->

                    </div>

                    <!-- Title and Description -->
                    <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                        echo $popup_ui_values->popupTextColor;
                    } else {
                        echo "black";
                    } ?>">Two-Factor Authentication</h2>
                    <p>To secure your account, please provide your phone number for two-factor authentication.</p>
                    <br><br>

                    <!-- Phone Number Input -->
                    <div class="phone-input-container">
                        <?php countrycode($popup_ui_values); ?>
                        <input type="number" class="phone-number-input" placeholder="Enter your number" name="phone"
                               required/>
                    </div>
                    <br>

                    <!-- Submit Button -->
                    <button type="submit" class="btn-primary"
                            style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>" style="">Send OTP
                    </button>
                </div>
            </form>

            <!-- Passcode Verification Form -2 -->
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <input type="hidden" name="mopostoption" value="movalotp">
                <input type="hidden" name="savestep" value="OOW">
                <input type="hidden" id="Passcode" name="Passcode">

                <!-- Display passcode verification if previous step exists -->
                <div style="<?php echo isset($request['showdiv']) ? 'display: block;' : 'display: none;'; ?>">
                    <input type="hidden" name="phone" value="<?php echo htmlspecialchars($request['phone'] ?? ''); ?>">
                    <input type="hidden" name="countrycode"
                           value="<?php echo htmlspecialchars($request['countrycode'] ?? ''); ?>">

                    <div class="container_new" style="background-color: <?php
                    if (isset($popup_ui_values->popupBgColor)) {
                        echo $popup_ui_values->popupBgColor;
                    } else {
                        echo "white";
                    }
                    ?>">
                        <div class="top_icon">
                            <!-- Back button for SMS verification -->
                            <a href="#" class="back-button"
                               style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                   echo $popup_ui_values->popupBtnColor;
                               } else {
                                   echo "#ff8500";
                               } ?>"
                               onclick="previousStep()">← Back</a>

                        </div>

                        <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                            echo $popup_ui_values->popupTextColor;
                        } else {
                            echo "black";
                        } ?>">Two-Factor Authentication</h2>

                        <!-- Display messages (success or error) -->
                        <div class="message_container"
                             style="color: <?php echo $error ? '#721c24' : '#155724'; ?>; background-color:
                             <?php echo $error ? '#f8d7da' : '#d4edda'; ?>; border: 0.1rem solid <?php echo $error ? '#f5c6cb' : '#c3e6cb'; ?>;">
                            <?php if (isset($request['message']) && !$error): ?>
                                <?php echo $request['message']; ?>
                            <?php elseif ($error): ?>
                                <?php showerrormessage($popup_ui_values); ?>
                            <?php endif; ?>
                        </div>

                        <!-- OTP Input -->
                        <div class="input-group" id="moPass">
                            <?php for ($i = 1; $i <= $otp_length; $i++): ?>
                                <input type="text" maxlength="1" inputmode="numeric"
                                       aria-label="Verification Code Digit <?php echo $i; ?>">
                            <?php endfor; ?>
                        </div>

                        <!-- Device Remember Option if applicable -->
                        <?php if ($is_device_based_enabled && $is_device_limit_exceeded): ?>
                            <div class="customer_row" style="margin-top: 15px; margin-bottom: 10px;">
                                <div class="col-sm-12">
                                    <input type="checkbox" id="rememberDevice" name="rememberDevice" value="1"
                                           style="margin-right: 10px;">
                                    <label for="rememberDevice">Remember My Device</label>
                                </div>
                            </div>
                        <?php endif; ?>

                        <!-- Verify Button -->
                        <button class="btn-primary"
                                style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                    echo $popup_ui_values->popupBtnColor;
                                } else {
                                    echo "#ff8500";
                                } ?>">Verify
                        </button>

                        <!-- Secondary Actions (Skip 2FA, Resend Code) -->
                        <div class="secondary-actions"
                             style="display: flex; margin-top: 20px; align-content: center; justify-content: space-between; align-items: center;">
                            <?php if ($customer_skip_twofa == 1) { ?>
                                <?php echo $formKey; ?>
                                <div class="skipTwoFa_section">
                                    <form method="post" name="skip-twoFA-remind" action="<?php echo $formPostUrl; ?>">
                                        <?php echo $formKey; ?>
                                        <input type="hidden" name="skiptwofa" value="skip_twofa">
                                        <button class="skip_button"
                                                style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                                    echo $popup_ui_values->popupBtnColor;
                                                } else {
                                                    echo "#ff8500";
                                                } ?>" type="submit">Remind Me Later
                                        </button>
                                    </form>
                                </div>
                            <?php } ?>
                            <a href="#" style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>" class="resend-link">Resend Code</a>
                        </div>
                    </div>
                </div>
            </form>

            <!-- JavaScript for Passcode Input -->
            <script>

                function previousStep() {
                    window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
                }

                function SMS_previousStep() {
                    window.location.href = "?mooption=invokeInline&step=OOWMethodValidation&savestep=OOS";
                }

                function redirectToLoginPage() {
                    const loginPageUrl = "<?php echo $loginPageUrl; ?>";
                    window.location.href = loginPageUrl;
                }

                window.onload = function () {
                    document.getElementById("redirect_to").value = window.location;
                };
            </script>
        </div>
    </div>
    </body>
    <?php
}


function OOEMethodValidation($formKey, $formPostUrl, $error, $request, $active_method_number, $loginPageUrl, $popup_ui_values, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length)
{
    ?>
    <body style="background-size: 100% 100%; background-color: <?php if (isset($popup_ui_values->BgColor)) {
        echo $popup_ui_values->BgColor;
    } else {
        echo "white";
    }
    ?>">

    <div class="customer_card container_new" style="background-color: <?php
    if (isset($popup_ui_values->popupBgColor)) {
        echo $popup_ui_values->popupBgColor;
    } else {
        echo "white";
    }
    ?>">
        <div class="top_icon">
            <div class="back-button">
                <?php if ($active_method_number == 1) { ?>
                    <!-- If active method number is 1, link to the login page -->
                    <a href="<?php echo $loginPageUrl; ?>" class="back-button help-dropdown"
                       style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                           echo $popup_ui_values->popupBtnColor;
                       } else {
                           echo "#ff8500";
                       } ?>">← Back</a>
                <?php } else { ?>
                    <!-- Otherwise, call the previousStep function -->
                    <a href="#" class="back-button help-dropdown"
                       style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                           echo $popup_ui_values->popupBtnColor;
                       } else {
                           echo "#ff8500";
                       } ?>;border:none;" onclick="previousStep()">← Back</a>
                <?php } ?>
            </div>
            <a href="#" style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                echo $popup_ui_values->popupBtnColor;
            } else {
                echo "#ff8500";
            } ?>" class="help-dropdown">Help?</a>
        </div>
        <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
            echo $popup_ui_values->popupTextColor;
        } else {
            echo "black";
        } ?>">Two-Factor Authentication</h2>

        <div class="message_container"
             style="color: <?php echo $error ? '#721c24' : '#155724'; ?>; background-color: <?php echo $error ? '#f8d7da' : '#d4edda'; ?>; border: 0.1rem solid <?php echo $error ? '#f5c6cb' : '#c3e6cb'; ?>;">
            <?php if (isset($request['message']) && !$error): ?>
                <?php echo $request['message']; ?>
            <?php elseif ($error): ?>
                <?php showerrormessage($popup_ui_values); ?>
            <?php endif; ?>
        </div>

        <div class="card-description">
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <input type="hidden" name="mopostoption" value="movalotp">
                <input type="hidden" name="savestep" value="OOE">
                <input type="hidden" id="Passcode" name="Passcode">

                <div class="customer_row">
                    <br>
                    <div class="input-group" id="moPass">
                        <?php for ($i = 1; $i <= $otp_length; $i++): ?>
                            <input type="text" maxlength="1" inputmode="numeric"
                                   aria-label="Verification Code Digit <?php echo $i; ?>">
                        <?php endfor; ?>
                    </div>
                </div>

                <?php if ($is_device_based_enabled && $is_device_limit_exceeded): ?>
                    <div class="customer_row" style="margin-top: 15px; margin-bottom: 10px;">
                        <div class="col-sm-12">
                            <input type="checkbox" id="rememberDevice" name="rememberDevice" value="1"
                                   style="margin-right: 10px;">
                            <label for="rememberDevice" style="font-weight: normal;">Remember My Device</label>
                        </div>
                    </div>
                <?php endif; ?>

                <br>
                <button class="btn-primary" style="background-color: <?php
                if (isset($popup_ui_values->popupBtnColor)) {
                    echo $popup_ui_values->popupBtnColor;
                } else {
                    echo "#ff8500";
                }
                ?>">Verify
                </button>
            </form>

            <div class="secondary-actions"
                 style="display: flex; margin-top: 20px; align-content: center; justify-content: space-between; align-items: center;">
                <?php if ($customer_skip_twofa == 1) { ?>
                    <?php echo $formKey; ?>
                    <div class="skipTwoFa_section">
                        <form method="post" name="skip-twoFA-remind" action="<?php echo $formPostUrl; ?>">
                            <?php echo $formKey; ?>
                            <input type="hidden" name="skiptwofa" value="skip_twofa">
                            <!-- Replace the button with a link -->
                            <button class="skip_button" style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>" type="submit">Remind Me Later
                            </button>
                        </form>
                    </div>
                <?php } ?>
                <a href="#" style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                    echo $popup_ui_values->popupBtnColor;
                } else {
                    echo "#ff8500";
                } ?>" class="resend-link">Resend Code</a>
            </div>

        </div>
    </div>

    <script type="text/javascript">

        function codeAddress() {
            var redirectElement = document.getElementById("redirect_to");
            if (redirectElement) {
                redirectElement.value = window.location;
            }
        }

        window.onload = codeAddress;

        function previousStep() {
            window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
        }

    </script>

    </body>
    <?php
}

function AMethodValidation($formKey, $formPostUrl, $AuthUrl, $issuer, $QrcodeJS, $error, $active_method_number, $loginPageUrl, $popup_ui_values, $secret, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $request, $otp_length)
{
    // Check if the user is on the "add passcode" step
    $isAddPasscodeStep = isset($request['addPasscode']) && $request['addPasscode'] == 'true';

    if ($AuthUrl !== false) {
        ?>
        <body style="background-size: 100% 100%;background-color: <?php if (isset($popup_ui_values->BgColor)) {
            echo $popup_ui_values->BgColor;
        } else {
            echo "white";
        } ?> ">
        <div class="customer_card container_new" style="background-color: <?php
        if (isset($popup_ui_values->popupBgColor)) {
            echo $popup_ui_values->popupBgColor;
        } else {
            echo "white";
        }
        ?>">
            <!-- Check if it's Step 1 or Step 2 (Passcode) -->
            <?php if (!$isAddPasscodeStep) { ?>

                <!-- Step 1: Google Authenticator Setup -->
                <div class="top_icon">
                    <div class="back-button">
                        <?php if ($active_method_number == 1) { ?>
                            <form method="post" action="<?php echo $loginPageUrl; ?>">
                                <a href="<?php echo $loginPageUrl; ?>" class="back-button" style="color: #ff8500; ">←
                                    Back</a>
                            </form>
                        <?php } else { ?>
                            <div class="back-button" onclick="previousStep()" type="button">← Back</div>
                        <?php } ?>
                    </div>
                </div>
                <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                    echo $popup_ui_values->popupTextColor;
                } else {
                    echo "black";
                } ?>">Set Up Authenticator</h2>
                <div class="authenticator_steps"
                     style="max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;">
                    <div class="card-description">


                        <!-- Instructions for setting up Google Authenticator -->
                        <ol style="list-style-type: none; padding-left: 0; margin-top: 20px;">
                            <li style="display: flex; align-items: center;text-align:left;justify-content: space-around;">
                                <label for="authenticator">Authenticator App:</label>
                                <p style="color: #777; margin: 5px 0 0 25px;">
                                    <select id="authenticator" name="authenticator" class="authenticator-dropdown">
                                        <option value="google">Google Authenticator</option>
                                        <option value="microsoft">Microsoft Authenticator</option>
                                        <option value="authy">Authy</option>
                                        <option value="lastpass">LastPass Authenticator</option>
                                    </select>

                                </p>

                            </li>
                            <li style="display: flex; align-items: center;text-align:left">
                                <i class="fas fa-download"
                                   style="font-size: 1.5em; color: #ff8500; margin-right: 10px;"></i>
                                <p style="color: #777; margin: 5px 0 0 25px;"><strong>Step 1:</strong> Download and open
                                    the <b>Selected Authenticator</b> app on your device.</p>

                            </li>
                            <li style="display: flex; align-items: center; margin-top: 10px;text-align:left">
                                <i class="fas fa-qrcode"
                                   style="font-size: 1.5em; color: #ff8500; margin-right: 10px;"></i>
                                <p style="color: #777; margin: 5px 0 0 25px;"><strong>Step 2:</strong> Scan the QR code
                                    below or manually enter the code into the app.</p>
                            </li>
                        </ol>
                        <hr style="border: 1px solid #ddd; margin-top: 20px;">
                    </div>
                </div>

                <div class="scanner_name_text"
                     style="display: flex; align-items: center; justify-content: space-around; gap: 3%;">
                    <div class="mo2f_gauth" id="displayGAQrCodeTour" style="background: white;"
                         data-qrcode="<?php echo $AuthUrl; ?>"></div>
                    <div id="qrcode"></div>
                    <div class="scanner_text"
                         style="background-color: #fff; padding: 5px; border-radius: 8px; text-align: center; color: #333; font-family: Arial, sans-serif; border: 2px dotted #ff8500;">
                        <div style="position: relative;">
                            <!-- Manual Entry Key with Copy Function -->
                            <p onclick="copyKey()">
                                <b>Manual Entry Key:</b>
                                <span id="manualKey"><?php echo $secret; ?></span>
                                <span id="copiedMessage">Copied!</span>
                                <i class="fas fa-copy" onclick="copyKey()" title="Copy Key"></i>
                            </p>
                        </div>
                        <h5 style="margin-top: 10px; color: #333;">App Name: <b
                                style="color:#ff8500"><?php echo $issuer; ?></b></h5>
                    </div>
                </div>
                <hr style="border: 1px solid #ddd; margin-top: 20px;">

                <div class="authenticator_steps"
                     style="max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;">
                    <div class="card-description">
                        <ol style="list-style-type: none; padding-left: 0; margin-top: 20px;">
                            <li style="display:flex;text-align:left">
                                <div style="display: flex; align-items: center;">
                                    <i class="fas fa-check"
                                       style="font-size: 1.5em; color: #ff8500; margin-right: 10px;"></i>
                                </div>
                                <p style="color: #777; margin: 5px 0 0 25px;"><strong>Step 3:</strong> Once you get the
                                    OTP code on your <b>Authenticator</b>, click <b>Next</b> below and enter the
                                    code.</p>
                            </li>
                        </ol>
                    </div>
                </div>

                <!-- Form to go to next step -->
                <form method="get" action="">
                    <input type="hidden" name="mooption" value="invokeInline">
                    <input type="hidden" name="step" value="GAMethodValidation">
                    <input type="hidden" name="savestep" value="value selected">
                    <input type="hidden" name="addPasscode" value="true">
                    <button type="submit" class="customer_btn btn-primary"
                            style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>">Next
                    </button>
                </form>

                <!-- JavaScript QR code generation -->
                <script src="<?php echo $QrcodeJS; ?>"></script>
                <!-- update : getting issue with require in Hyva theme -->
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
                <script>
                jQuery(document).ready(function($) {
                    new QRCode(document.getElementById("qrcode"), $('.mo2f_gauth').data('qrcode'));
                });
                </script>

                <script type="text/javascript">
                    // Go back to the previous step
                    function previousStep() {
                        window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
                    }

                    // Copy the manual entry key to clipboard
                    function copyKey() {
                        const keyElement = document.getElementById('manualKey');
                        const copiedMessage = document.getElementById('copiedMessage');

                        // Copy the key to clipboard
                        navigator.clipboard.writeText(keyElement.textContent)
                            .then(() => {
                                // Show "Copied!" message
                                copiedMessage.classList.add('show');

                                // Hide it after 2 seconds
                                setTimeout(() => {
                                    copiedMessage.classList.remove('show');
                                }, 800);
                            })
                            .catch(err => {
                                console.error('Failed to copy the key: ', err);
                            });
                    }
                </script>
            <?php } else { ?>
            <!-- Step 2: Enter Passcode (OTP) -->
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <input type="hidden" name="mopostoption" value="movalotp">
                <input type="hidden" name="savestep" value="GoogleAuthenticator">
                <input type="hidden" id="Passcode" name="Passcode">

                <div class="container_new" style="background-color: <?php
                if (isset($popup_ui_values->popupBgColor)) {
                    echo $popup_ui_values->popupBgColor;
                } else {
                    echo "white";
                }
                ?>">
                    <div class="top_icon">
                        <div class="back-button" onclick="authenticator_verify_previousStep()" type="button"
                             style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                 echo $popup_ui_values->popupBtnColor;
                             } else {
                                 echo "#ff8500";
                             } ?>">←
                            Back
                        </div>

                    </div>
                    <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                        echo $popup_ui_values->popupTextColor;
                    } else {
                        echo "black";
                    } ?>">Enter Authenticator Passcode</h2>

                    <!-- Error or Success Message -->
                    <div class="message_container" style="
                        color: <?php echo $error ? '#721c24' : '#155724'; ?>;
                        background-color: <?php echo $error ? '#f8d7da' : '#d4edda'; ?>;
                        border: 0.1rem solid <?php echo $error ? '#f5c6cb' : '#c3e6cb'; ?>;">
                        <?php if ($error): ?>
                            <?php showerrormessage($popup_ui_values); ?>
                        <?php else: ?>
                            <div class="success_message" style="--success-message-text:
                            <?php echo isset($popup_ui_values->popup_ui_success_text_color) ? htmlspecialchars($popup_ui_values->popup_ui_success_text_color) : '#155724'; ?>;">
                                Enter the code you scanned from the Google Authenticator app to complete the
                                validation.
                            </div>
                        <?php endif; ?>
                    </div>

                    <br>
                    <div class="input-group" id="moPass">
                        <?php for ($i = 1; $i <= $otp_length; $i++): ?>
                            <!-- Dynamic OTP Input Fields -->
                            <input type="text" maxlength="1" inputmode="numeric"
                                   aria-label="Verification Code Digit <?php echo $i; ?>" class="otp-input">
                        <?php endfor; ?>
                    </div>

                    <!-- Device Remember Option (only if limits exceeded) -->
                    <?php if ($is_device_based_enabled && $is_device_limit_exceeded): ?>
                        <div class="customer_row" style="margin-top: 15px; margin-bottom: 10px;">
                            <div class="col-sm-12">
                                <input type="checkbox" id="rememberDevice" name="rememberDevice" value="1"
                                       style="margin-right: 10px;">
                                <label for="rememberDevice">Remember My Device</label>
                            </div>
                        </div>
                    <?php endif; ?>

                    <br>
                    <button class="btn-primary"
                            style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>">Verify
                    </button>
            </form>

            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <!-- Skip for Now Option -->
                <div class="secondary-actions" style="display: flex; margin-top: 10px;">
                    <?php if ($customer_skip_twofa == 1) { ?>
                        <?php echo $formKey; ?>
                        <div class="skipTwoFa_section">
                            <form method="post" name="skip-twoFA-remind" action="<?php echo $formPostUrl; ?>">
                                <?php echo $formKey; ?>
                                <input type="hidden" name="skiptwofa" value="skip_twofa">
                                <button class="skip_button"
                                        style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                            echo $popup_ui_values->popupBtnColor;
                                        } else {
                                            echo "#ff8500";
                                        } ?>" type="submit">Remind Me Later
                                </button>
                            </form>
                        </div>
                    <?php } ?>
                </div>
        </div>
        </form>

        <script type="text/javascript">

            // Handle back to previous step
            function authenticator_verify_previousStep() {
                window.location.href = "?mooption=invokeInline&step=GAMethodValidation";
            }
        </script>
        <?php } ?>
        </div>
        </body>
        <?php
    } else {
        print_r("Something went wrong! Please try again");
        ?>
        <button class="default-btn" onclick="previousStep()" type="button">Back</button>
        <br><br>
        <script type="text/javascript">
            function previousStep() {
                window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
            }

            function codeAddress() {
                var redirectElement = document.getElementById("redirect_to");
                if (redirectElement) {
                    redirectElement.value = window.location;
                }
            }

            window.onload = codeAddress;
        </script>
        <?php
    }
}

function MicrosoftAuthMethodValidation($formKey, $formPostUrl, $AuthUrl, $issuer, $QrcodeJS, $error, $active_method_number, $loginPageUrl, $popup_ui_values, $secret, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $request, $otp_length)
{
    // Check if the user is on the "add passcode" step
    $isAddPasscodeStep = isset($request['addPasscode']) && $request['addPasscode'] == 'true';

    if ($AuthUrl !== false) {
        ?>
        <body style="background-size: 100% 100%;background-color: <?php if (isset($popup_ui_values->BgColor)) {
            echo $popup_ui_values->BgColor;
        } else {
            echo "white";
        } ?> ">
        <div class="customer_card container_new" style="background-color: <?php
        if (isset($popup_ui_values->popupBgColor)) {
            echo $popup_ui_values->popupBgColor;
        } else {
            echo "white";
        }
        ?>">
            <!-- Check if it's Step 1 or Step 2 (Passcode) -->
            <?php if (!$isAddPasscodeStep) { ?>

                <!-- Step 1: Google Authenticator Setup -->
                <div class="top_icon">
                    <div class="back-button">
                        <?php if ($active_method_number == 1) { ?>
                            <form method="post" action="<?php echo $loginPageUrl; ?>">
                                <a href="<?php echo $loginPageUrl; ?>" class="back-button" style="color: #ff8500; ">←
                                    Back</a>
                            </form>
                        <?php } else { ?>
                            <div class="back-button" onclick="previousStep()" type="button">← Back</div>
                        <?php } ?>
                    </div>
                </div>
                <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                    echo $popup_ui_values->popupTextColor;
                } else {
                    echo "black";
                } ?>">Set Up Microsoft Authenticator</h2>
                <div class="authenticator_steps"
                     style="max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;">
                    <div class="card-description">


                        <!-- Instructions for setting up Google Authenticator -->
                        <ol style="list-style-type: none; padding-left: 0; margin-top: 20px;">

                            <li style="display: flex; align-items: center;text-align:left">
                                <i class="fas fa-download"
                                   style="font-size: 1.5em; color: #ff8500; margin-right: 10px;"></i>
                                <p style="color: #777; margin: 5px 0 0 25px;"><strong>Step 1:</strong> Download and open
                                    the <b>Microsoft Authenticator</b> app on your device.</p>

                            </li>
                            <li style="display: flex; align-items: center; margin-top: 10px;text-align:left">
                                <i class="fas fa-qrcode"
                                   style="font-size: 1.5em; color: #ff8500; margin-right: 10px;"></i>
                                <p style="color: #777; margin: 5px 0 0 25px;"><strong>Step 2:</strong> Scan the QR code
                                    below or manually enter the code into the app.</p>
                            </li>
                        </ol>
                        <hr style="border: 1px solid #ddd; margin-top: 20px;">
                    </div>
                </div>

                <div class="scanner_name_text"
                     style="display: flex; align-items: center; justify-content: space-around; gap: 3%;">
                    <div class="mo2f_gauth" id="displayGAQrCodeTour" style="background: white;"
                         data-qrcode="<?php echo $AuthUrl; ?>"></div>
                    <div id="qrcode"></div>
                    <div class="scanner_text"
                         style="background-color: #fff; padding: 5px; border-radius: 8px; text-align: center; color: #333; font-family: Arial, sans-serif; border: 2px dotted #ff8500;">
                        <div style="position: relative;">
                            <!-- Manual Entry Key with Copy Function -->
                            <p onclick="copyKey()">
                                <b>Manual Entry Key:</b>
                                <span id="manualKey"><?php echo $secret; ?></span>
                                <span id="copiedMessage">Copied!</span>
                                <i class="fas fa-copy" onclick="copyKey()" title="Copy Key"></i>
                            </p>
                        </div>
                        <h5 style="margin-top: 10px; color: #333;">App Name: <b
                                style="color:#ff8500"><?php echo $issuer; ?></b></h5>
                    </div>
                </div>
                <hr style="border: 1px solid #ddd; margin-top: 20px;">

                <div class="authenticator_steps"
                     style="max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;">
                    <div class="card-description">
                        <ol style="list-style-type: none; padding-left: 0; margin-top: 20px;">
                            <li style="display:flex;text-align:left">
                                <div style="display: flex; align-items: center;">
                                    <i class="fas fa-check"
                                       style="font-size: 1.5em; color: #ff8500; margin-right: 10px;"></i>
                                </div>
                                <p style="color: #777; margin: 5px 0 0 25px;"><strong>Step 3:</strong> Once you get the
                                    OTP code on your <b>Microsoft Authenticator</b>, click <b>Next</b> below and enter
                                    the
                                    code.</p>
                            </li>
                        </ol>
                    </div>
                </div>

                <!-- Form to go to next step -->
                <form method="get" action="">
                    <input type="hidden" name="mooption" value="invokeInline">
                    <input type="hidden" name="step" value="MicrosoftAuthenticator">
                    <input type="hidden" name="savestep" value="MicrosoftAuthenticator">
                    <input type="hidden" name="addPasscode" value="true">
                    <button type="submit" class="customer_btn btn-primary"
                            style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>">Next
                    </button>
                </form>

                <!-- JavaScript QR code generation -->
                <script src="<?php echo $QrcodeJS; ?>"></script>
                <!-- update : getting issue with require in Hyva theme -->
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
                <script>
                jQuery(document).ready(function($) {
                    new QRCode(document.getElementById("qrcode"), $('.mo2f_gauth').data('qrcode'));
                });
                </script>

                <script type="text/javascript">
                    // Go back to the previous step
                    function previousStep() {
                        window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
                    }

                    // Copy the manual entry key to clipboard
                    function copyKey() {
                        const keyElement = document.getElementById('manualKey');
                        const copiedMessage = document.getElementById('copiedMessage');

                        // Copy the key to clipboard
                        navigator.clipboard.writeText(keyElement.textContent)
                            .then(() => {
                                // Show "Copied!" message
                                copiedMessage.classList.add('show');

                                // Hide it after 2 seconds
                                setTimeout(() => {
                                    copiedMessage.classList.remove('show');
                                }, 800);
                            })
                            .catch(err => {
                                console.error('Failed to copy the key: ', err);
                            });
                    }
                </script>
            <?php } else { ?>
            <!-- Step 2: Enter Passcode (OTP) -->
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <input type="hidden" name="mopostoption" value="movalotp">
                <input type="hidden" name="savestep" value="MicrosoftAuthenticator">
                <input type="hidden" id="Passcode" name="Passcode">

                <div class="container_new" style="background-color: <?php
                if (isset($popup_ui_values->popupBgColor)) {
                    echo $popup_ui_values->popupBgColor;
                } else {
                    echo "white";
                }
                ?>">
                    <div class="top_icon">
                        <div class="back-button" onclick="authenticator_verify_previousStep()" type="button"
                             style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                 echo $popup_ui_values->popupBtnColor;
                             } else {
                                 echo "#ff8500";
                             } ?>">←
                            Back
                        </div>

                    </div>
                    <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                        echo $popup_ui_values->popupTextColor;
                    } else {
                        echo "black";
                    } ?>">Enter Authenticator Passcode</h2>

                    <!-- Error or Success Message -->
                    <div class="message_container" style="
                        color: <?php echo $error ? '#721c24' : '#155724'; ?>;
                        background-color: <?php echo $error ? '#f8d7da' : '#d4edda'; ?>;
                        border: 0.1rem solid <?php echo $error ? '#f5c6cb' : '#c3e6cb'; ?>;">
                        <?php if ($error): ?>
                            <?php showerrormessage($popup_ui_values); ?>
                        <?php else: ?>
                            <div class="success_message" style="--success-message-text:
                            <?php echo isset($popup_ui_values->popup_ui_success_text_color) ? htmlspecialchars($popup_ui_values->popup_ui_success_text_color) : '#155724'; ?>;">
                                Enter the code you scanned from the Microsoft Authenticator app to complete the
                                validation.
                            </div>
                        <?php endif; ?>
                    </div>

                    <br>
                    <div class="input-group" id="moPass">
                        <?php for ($i = 1; $i <= $otp_length; $i++): ?>
                            <!-- Dynamic OTP Input Fields -->
                            <input type="text" maxlength="1" inputmode="numeric"
                                   aria-label="Verification Code Digit <?php echo $i; ?>" class="otp-input">
                        <?php endfor; ?>
                    </div>

                    <!-- Device Remember Option (only if limits exceeded) -->
                    <?php if ($is_device_based_enabled && $is_device_limit_exceeded): ?>
                        <div class="customer_row" style="margin-top: 15px; margin-bottom: 10px;">
                            <div class="col-sm-12">
                                <input type="checkbox" id="rememberDevice" name="rememberDevice" value="1"
                                       style="margin-right: 10px;">
                                <label for="rememberDevice">Remember My Device</label>
                            </div>
                        </div>
                    <?php endif; ?>

                    <br>
                    <button class="btn-primary"
                            style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>">Verify
                    </button>
            </form>

            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <!-- Skip for Now Option -->
                <div class="secondary-actions" style="display: flex; margin-top: 10px;">
                    <?php if ($customer_skip_twofa == 1) { ?>
                        <?php echo $formKey; ?>
                        <div class="skipTwoFa_section">
                            <form method="post" name="skip-twoFA-remind" action="<?php echo $formPostUrl; ?>">
                                <?php echo $formKey; ?>
                                <input type="hidden" name="skiptwofa" value="skip_twofa">
                                <button class="skip_button"
                                        style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                            echo $popup_ui_values->popupBtnColor;
                                        } else {
                                            echo "#ff8500";
                                        } ?>" type="submit">Remind Me Later
                                </button>
                            </form>
                        </div>
                    <?php } ?>
                </div>
        </div>
        </form>

        <script type="text/javascript">

            // Handle back to previous step
            function authenticator_verify_previousStep() {
                window.location.href = "?mooption=invokeInline&step=MicrosoftAuthenticator";
            }
        </script>
        <?php } ?>
        </div>
        </body>
        <?php
    } else {
        print_r("Something went wrong! Please try again");
        ?>
        <button class="default-btn" onclick="previousStep()" type="button">Back</button>
        <br><br>
        <script type="text/javascript">
            function previousStep() {
                window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
            }

            function codeAddress() {
                var redirectElement = document.getElementById("redirect_to");
                if (redirectElement) {
                    redirectElement.value = window.location;
                }
            }

            window.onload = codeAddress;
        </script>
        <?php
    }
}

function GAMethodValidation($formKey, $formPostUrl, $AuthUrl, $issuer, $QrcodeJS, $error, $active_method_number, $loginPageUrl, $popup_ui_values, $secret, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $request, $otp_length)
{
    // Check if the user is on the "add passcode" step
    $isAddPasscodeStep = isset($request['addPasscode']) && $request['addPasscode'] == 'true';

    if ($AuthUrl !== false) {
        ?>
        <body style="background-size: 100% 100%;background-color: <?php if (isset($popup_ui_values->BgColor)) {
            echo $popup_ui_values->BgColor;
        } else {
            echo "white";
        } ?> ">
        <div class="customer_card container_new" style="background-color: <?php
        if (isset($popup_ui_values->popupBgColor)) {
            echo $popup_ui_values->popupBgColor;
        } else {
            echo "white";
        }
        ?>">
            <!-- Check if it's Step 1 or Step 2 (Passcode) -->
            <?php if (!$isAddPasscodeStep) { ?>

                <!-- Step 1: Google Authenticator Setup -->
                <div class="top_icon">
                    <div class="back-button">
                        <?php if ($active_method_number == 1) { ?>
                            <form method="post" action="<?php echo $loginPageUrl; ?>">
                                <a href="<?php echo $loginPageUrl; ?>" class="back-button" style="color: #ff8500; ">←
                                    Back</a>
                            </form>
                        <?php } else { ?>
                            <div class="back-button" onclick="previousStep()" type="button">← Back</div>
                        <?php } ?>
                    </div>
                </div>
                <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                    echo $popup_ui_values->popupTextColor;
                } else {
                    echo "black";
                } ?>">Set Up Google Authenticator</h2>
                <div class="authenticator_steps"
                     style="max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;">
                    <div class="card-description">


                        <!-- Instructions for setting up Google Authenticator -->
                        <ol style="list-style-type: none; padding-left: 0; margin-top: 20px;">

                            <li style="display: flex; align-items: center;text-align:left">
                                <i class="fas fa-download"
                                   style="font-size: 1.5em; color: #ff8500; margin-right: 10px;"></i>
                                <p style="color: #777; margin: 5px 0 0 25px;"><strong>Step 1:</strong> Download and open
                                    the <b>Google Authenticator</b> app on your device.</p>

                            </li>
                            <li style="display: flex; align-items: center; margin-top: 10px;text-align:left">
                                <i class="fas fa-qrcode"
                                   style="font-size: 1.5em; color: #ff8500; margin-right: 10px;"></i>
                                <p style="color: #777; margin: 5px 0 0 25px;"><strong>Step 2:</strong> Scan the QR code
                                    below or manually enter the code into the app.</p>
                            </li>
                        </ol>
                        <hr style="border: 1px solid #ddd; margin-top: 20px;">
                    </div>
                </div>

                <div class="scanner_name_text"
                     style="display: flex; align-items: center; justify-content: space-around; gap: 3%;">
                    <div class="mo2f_gauth" id="displayGAQrCodeTour" style="background: white;"
                         data-qrcode="<?php echo $AuthUrl; ?>"></div>
                    <div id="qrcode"></div>
                    <div class="scanner_text"
                         style="background-color: #fff; padding: 5px; border-radius: 8px; text-align: center; color: #333; font-family: Arial, sans-serif; border: 2px dotted #ff8500;">
                        <div style="position: relative;">
                            <!-- Manual Entry Key with Copy Function -->
                            <p onclick="copyKey()">
                                <b>Manual Entry Key:</b>
                                <span id="manualKey"><?php echo $secret; ?></span>
                                <span id="copiedMessage">Copied!</span>
                                <i class="fas fa-copy" onclick="copyKey()" title="Copy Key"></i>
                            </p>
                        </div>
                        <h5 style="margin-top: 10px; color: #333;">App Name: <b
                                style="color:#ff8500"><?php echo $issuer; ?></b></h5>
                    </div>
                </div>
                <hr style="border: 1px solid #ddd; margin-top: 20px;">

                <div class="authenticator_steps"
                     style="max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;">
                    <div class="card-description">
                        <ol style="list-style-type: none; padding-left: 0; margin-top: 20px;">
                            <li style="display:flex;text-align:left">
                                <div style="display: flex; align-items: center;">
                                    <i class="fas fa-check"
                                       style="font-size: 1.5em; color: #ff8500; margin-right: 10px;"></i>
                                </div>
                                <p style="color: #777; margin: 5px 0 0 25px;"><strong>Step 3:</strong> Once you get the
                                    OTP code on your <b>Google Authenticator</b>, click <b>Next</b> below and enter the
                                    code.</p>
                            </li>
                        </ol>
                    </div>
                </div>

                <!-- Form to go to next step -->
                <form method="get" action="">
                    <input type="hidden" name="mooption" value="invokeInline">
                    <input type="hidden" name="step" value="GAMethodValidation">
                    <input type="hidden" name="savestep" value="GoogleAuthenticator">
                    <input type="hidden" name="addPasscode" value="true">
                    <button type="submit" class="customer_btn btn-primary"
                            style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>">Next
                    </button>
                </form>

                <!-- JavaScript QR code generation -->
                <script src="<?php echo $QrcodeJS; ?>"></script>
                <!-- update : getting issue with require in Hyva theme -->
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
                <script>
                jQuery(document).ready(function($) {
                    new QRCode(document.getElementById("qrcode"), $('.mo2f_gauth').data('qrcode'));
                });
                </script>

                <script type="text/javascript">
                    // Go back to the previous step
                    function previousStep() {
                        window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
                    }

                    // Copy the manual entry key to clipboard
                    function copyKey() {
                        const keyElement = document.getElementById('manualKey');
                        const copiedMessage = document.getElementById('copiedMessage');

                        // Copy the key to clipboard
                        navigator.clipboard.writeText(keyElement.textContent)
                            .then(() => {
                                // Show "Copied!" message
                                copiedMessage.classList.add('show');

                                // Hide it after 2 seconds
                                setTimeout(() => {
                                    copiedMessage.classList.remove('show');
                                }, 800);
                            })
                            .catch(err => {
                                console.error('Failed to copy the key: ', err);
                            });
                    }
                </script>
            <?php } else { ?>
            <!-- Step 2: Enter Passcode (OTP) -->
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <input type="hidden" name="mopostoption" value="movalotp">
                <input type="hidden" name="savestep" value="GoogleAuthenticator">
                <input type="hidden" id="Passcode" name="Passcode">

                <div class="container_new" style="background-color: <?php
                if (isset($popup_ui_values->popupBgColor)) {
                    echo $popup_ui_values->popupBgColor;
                } else {
                    echo "white";
                }
                ?>">
                    <div class="top_icon">
                        <div class="back-button" onclick="authenticator_verify_previousStep()" type="button"
                             style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                 echo $popup_ui_values->popupBtnColor;
                             } else {
                                 echo "#ff8500";
                             } ?>">←
                            Back
                        </div>

                    </div>
                    <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                        echo $popup_ui_values->popupTextColor;
                    } else {
                        echo "black";
                    } ?>">Enter Authenticator Passcode</h2>

                    <!-- Error or Success Message -->
                    <div class="message_container" style="
                        color: <?php echo $error ? '#721c24' : '#155724'; ?>;
                        background-color: <?php echo $error ? '#f8d7da' : '#d4edda'; ?>;
                        border: 0.1rem solid <?php echo $error ? '#f5c6cb' : '#c3e6cb'; ?>;">
                        <?php if ($error): ?>
                            <?php showerrormessage($popup_ui_values); ?>
                        <?php else: ?>
                            <div class="success_message" style="--success-message-text:
                            <?php echo isset($popup_ui_values->popup_ui_success_text_color) ? htmlspecialchars($popup_ui_values->popup_ui_success_text_color) : '#155724'; ?>;">
                                Enter the code you scanned from the Google Authenticator app to complete the
                                validation.
                            </div>
                        <?php endif; ?>
                    </div>

                    <br>
                    <div class="input-group" id="moPass">
                        <?php for ($i = 1; $i <= $otp_length; $i++): ?>
                            <!-- Dynamic OTP Input Fields -->
                            <input type="text" maxlength="1" inputmode="numeric"
                                   aria-label="Verification Code Digit <?php echo $i; ?>" class="otp-input">
                        <?php endfor; ?>
                    </div>

                    <!-- Device Remember Option (only if limits exceeded) -->
                    <?php if ($is_device_based_enabled && $is_device_limit_exceeded): ?>
                        <div class="customer_row" style="margin-top: 15px; margin-bottom: 10px;">
                            <div class="col-sm-12">
                                <input type="checkbox" id="rememberDevice" name="rememberDevice" value="1"
                                       style="margin-right: 10px;">
                                <label for="rememberDevice">Remember My Device</label>
                            </div>
                        </div>
                    <?php endif; ?>

                    <br>
                    <button class="btn-primary"
                            style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>">Verify
                    </button>
            </form>

            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <!-- Skip for Now Option -->
                <div class="secondary-actions" style="display: flex; margin-top: 10px;">
                    <?php if ($customer_skip_twofa == 1) { ?>
                        <?php echo $formKey; ?>
                        <div class="skipTwoFa_section">
                            <form method="post" name="skip-twoFA-remind" action="<?php echo $formPostUrl; ?>">
                                <?php echo $formKey; ?>
                                <input type="hidden" name="skiptwofa" value="skip_twofa">
                                <button class="skip_button"
                                        style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                            echo $popup_ui_values->popupBtnColor;
                                        } else {
                                            echo "#ff8500";
                                        } ?>" type="submit">Remind Me Later
                                </button>
                            </form>
                        </div>
                    <?php } ?>
                </div>
        </div>
        </form>

        <script type="text/javascript">

            // Handle back to previous step
            function authenticator_verify_previousStep() {
                window.location.href = "?mooption=invokeInline&step=GAMethodValidation";
            }
        </script>
        <?php } ?>
        </div>
        </body>
        <?php
    } else {
        print_r("Something went wrong! Please try again");
        ?>
        <button class="default-btn" onclick="previousStep()" type="button">Back</button>
        <br><br>
        <script type="text/javascript">
            function previousStep() {
                window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
            }

            function codeAddress() {
                var redirectElement = document.getElementById("redirect_to");
                if (redirectElement) {
                    redirectElement.value = window.location;
                }
            }

            window.onload = codeAddress;
        </script>
        <?php
    }
}


function OOSEMethodValidation($formKey, $formPostUrl, $error, $request, $active_method_number, $loginPageUrl, $popup_ui_values, $customer_skip_twofa, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length, $redirectUrl)
{
    ?>
    <body style="background-size: 100% 100%;background-color: <?php if (isset($popup_ui_values->BgColor)) {
        echo $popup_ui_values->BgColor;
    } else {
        echo "white";
    } ?> ">
    <div class="customer_card container_new" style="background-color: <?php if (isset($popup_ui_values->popupBgColor)) {
        echo $popup_ui_values->popupBgColor;
    } else {
        echo "white";
    }
    ?>">
        <br>

        <div class="card-description">
            <!-- First Form: Send OTP -->
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <div style="display: <?php echo isset($request['showdiv']) ? 'none' : 'block'; ?>;">
                    <div class="top_icon">
                        <div class="back-button">
                            <?php if ($active_method_number == 1) { ?>
                                <!-- If active method number is 1, link to the login page -->
                                <a href="<?php echo $loginPageUrl; ?>" class="back-button"
                                   style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                       echo $popup_ui_values->popupBtnColor;
                                   } else {
                                       echo "#ff8500";
                                   } ?>">← Back</a>
                            <?php } else { ?>
                                <!-- Otherwise, call the previousStep function -->
                                <div class="back-button"
                                     style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                         echo $popup_ui_values->popupBtnColor;
                                     } else {
                                         echo "#ff8500";
                                     } ?>" onclick="previousStep()">← Back
                                </div>
                            <?php } ?>
                        </div>

                    </div>
                    <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                        echo $popup_ui_values->popupTextColor;
                    } else {
                        echo "black";
                    } ?>">Two-Factor Authentication</h2>
                    <p>To secure your account, please verify your identity by providing your phone number and email
                        address for two-factor authentication.</p>

                    <input type="hidden" name="mopostoption" value="challenge">

                    <div class="customer_row">
                        <br>
                        <div class="phone-input-container"
                             style="display: flex; align-content: center; justify-content: center; align-items: center; gap: 3%;">
                            <!-- Country Code Dropdown -->
                            <?php countrycode($popup_ui_values); ?>

                            <!-- Phone Number Input -->
                            <input type="number" class="phone-number-input" placeholder="Enter your number" name="phone"
                                   required/>
                        </div>

                        <div
                            style="display: flex; align-items: center; gap: 12%; width: 100%; justify-content: center;">
                            <label class="col-sm-4">Email:</label>
                            <div class="col-sm-8">
                                <input type="hidden" name="email" value="<?php echo $request['useremail'] ?? ''; ?>">
                                <input type="text"
                                       style="background:white; color: '#000'; border: none; border-bottom: 2px solid #ff8500; width: 120%;"
                                       class="method-input-box" placeholder="Enter your email"
                                       value="<?php echo $request['useremail'] ?? ''; ?>" name="email" disabled/>
                            </div>
                            <input type="hidden" id="redirect_to" name="redirect_to" value="">
                        </div>
                        <br>
                        <input type="hidden" name="miniorangetfa_method" value="OOSE">
                        <button class="customer_btn btn-primary"
                                style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                    echo $popup_ui_values->popupBtnColor;
                                } else {
                                    echo "#ff8500";
                                } ?>" type="submit">Send OTP
                        </button>
                    </div>
                </div>
            </form>

            <!-- Second Form: Verify OTP -->
            <form method="post" action="<?php echo $formPostUrl; ?>">
                <?php echo $formKey; ?>
                <div style="display: <?php echo isset($request['showdiv']) ? 'block' : 'none'; ?>;">
                    <input type="hidden" name="mopostoption" value="movalotp">
                    <input type="hidden" name="savestep" value="OOSE">
                    <input type="hidden" id="Passcode" name="Passcode">
                    <input type="hidden" name="phone" value="<?php echo htmlspecialchars($request['phone'] ?? ''); ?>">
                    <input type="hidden" name="countrycode"
                           value="<?php echo htmlspecialchars($request['countrycode'] ?? ''); ?>">

                    <div class="container_new"
                         style="background-color: <?php if (isset($popup_ui_values->popupBgColor)) {
                             echo $popup_ui_values->popupBgColor;
                         } else {
                             echo "white";
                         } ?>">
                        <div class="top_icon">
                            <div class="back-button">
                                <?php
                                if ($active_method_number == 1 && isset($request['sendOTP_directly']) && $request['sendOTP_directly'] == 1) { ?>
                                    <!-- If active method number is 1, link to the login page -->
                                    <a href="<?php echo $loginPageUrl; ?>" class="back-button"
                                       style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                           echo $popup_ui_values->popupBtnColor;
                                       } else {
                                           echo "#ff8500";
                                       } ?>">← Back</a>
                                    <?php
                                } elseif ($active_method_number > 1) { ?>
                                    <!-- If active method number is greater than 1, link to the previous step -->
                                    <a class="back-button"
                                       style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                           echo $popup_ui_values->popupBtnColor;
                                       } else {
                                           echo "#ff8500";
                                       } ?>" onclick="previousStep()">← Back</a>
                                    <?php
                                } else { ?>
                                    <!-- Otherwise, call the OOSE_previousStep function -->
                                    <div class="back-button"
                                         style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                             echo $popup_ui_values->popupBtnColor;
                                         } else {
                                             echo "#ff8500";
                                         } ?>" onclick="previousStep()">← Back
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                        <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                            echo $popup_ui_values->popupTextColor;
                        } else {
                            echo "black";
                        } ?>">Two-Factor Authentication</h2>

                        <div class="message_container"
                             style="color: <?php echo $error ? '#721c24' : '#155724'; ?>; background-color: <?php echo $error ? '#f8d7da' : '#d4edda'; ?>; border: 0.1rem solid <?php echo $error ? '#f5c6cb' : '#c3e6cb'; ?>;">
                            <?php if (isset($request['message']) && !$error): ?>
                                <?php echo $request['message']; ?>
                            <?php elseif ($error): ?>
                                <?php showerrormessage($popup_ui_values); ?>
                            <?php endif; ?>
                        </div>

                        <br>
                        <div class="input-group" id="moPass">
                            <?php for ($i = 1; $i <= $otp_length; $i++): ?>
                                <input type="text" maxlength="1" inputmode="numeric"
                                       aria-label="Verification Code Digit <?php echo $i; ?>">
                            <?php endfor; ?>
                        </div>

                        <?php if ($is_device_based_enabled && $is_device_limit_exceeded): ?>
                            <div class="customer_row" style="margin-top: 15px; margin-bottom: 10px;">
                                <div class="col-sm-12">
                                    <input type="checkbox" id="rememberDevice" name="rememberDevice" value="1"
                                           style="margin-right: 10px;">
                                    <label for="rememberDevice">Remember My Device</label>
                                </div>
                            </div>
                        <?php endif; ?>
                        <br>
                        <button class="customer_btn btn-primary"
                                style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                    echo $popup_ui_values->popupBtnColor;
                                } else {
                                    echo "#ff8500";
                                } ?>" type="submit">Verify
                        </button>

            </form>

            <div class="secondary-actions"
                 style="display: flex; margin-top: 20px; align-content: center; justify-content: space-between; align-items: center;">
                <?php if ($customer_skip_twofa == 1) { ?>
                    <?php echo $formKey; ?>
                    <div class="skipTwoFa_section">
                        <form method="post" name="skip-twoFA-remind" action="<?php echo $formPostUrl; ?>">
                            <?php echo $formKey; ?>
                            <input type="hidden" name="skiptwofa" value="skip_twofa">
                            <!-- Replace the button with a link -->
                            <button class="skip_button" style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                echo $popup_ui_values->popupBtnColor;
                            } else {
                                echo "#ff8500";
                            } ?>" type="submit">Remind Me Later
                            </button>
                        </form>
                    </div>
                <?php } ?>
                <a href="#" style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                    echo $popup_ui_values->popupBtnColor;
                } else {
                    echo "#ff8500";
                } ?>" class="resend-link">Resend Code</a>
            </div>

        </div>
    </div>
    </div>
    </div>

    <script type="text/javascript">
        // Redirects to the previous step in the process
        function previousStep() {
            window.location.href = "?mooption=invokeInline&step=ChooseMFAMethod";
        }

        // Redirects to the OOSE previous step
        function OOSE_previousStep() {
            window.location.href = "?mooption=invokeInline&step=OOSEMethodValidation&savestep=OOSE";
        }

        // Updates the hidden "Passcode" field based on OTP input values
        document.getElementById("redirect_to").value = window.location;
    </script>
    </body>
    <?php

}


function InvalidRequest()
{
    ?>
    <div class="container" style="background: #f5f5f5">
        <div class="row">
            <div class="cards">
                <div class="card" style="background-color:white;"
                <div class="card-title">
                    <div class="col-sm-12">
                        <center>Invalid Request</center>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <?php
}

function ChooseMFAMethod($formKey, $activeMethods, $tfaArray, $formPostUrl, $loginPageUrl, $popup_ui_values, $customer_skip_twofa)
{
    // Define available MFA methods
    $methods = [
        'GoogleAuthenticator' => [
            'icon' => '<i class="fas fa-qrcode"></i>',
            'name' => 'Google Authenticator',
            'desc' => 'Authenticator App'
        ],
        'MicrosoftAuthenticator' => [
            'icon' => '<i class="fas fa-qrcode"></i>',
            'name' => 'Microsoft Authenticator',
            'desc' => 'Authenticator App'
        ],
        'OOS' => [
            'icon' => '<i class="fas fa-mobile-alt"></i>',
            'name' => 'SMS',
            'desc' => 'Send an SMS code to ***-***-5599'
        ],
        'OOE' => [
            'icon' => '<i class="fas fa-envelope"></i>',
            'name' => 'Email',
            'desc' => 'Send OTP to your email'
        ],
        'OOSE' => [
            'icon' => '<i class="fas fa-shield-alt"></i>',
            'name' => 'Email + SMS',
            'desc' => 'Send OTP to both email and SMS'
        ],
        'OOW' => [
            'icon' => '<i class="fab fa-whatsapp"></i>',
            'name' => 'WhatsApp',
            'desc' => 'Send code to WhatsApp ***-***-5599'
        ]
    ];
    ?>
    <body style="background-size:cover;background-color: <?php if (isset($popup_ui_values->BgColor)) {
        echo $popup_ui_values->BgColor;
    } else {
        echo "white";
    }
    ?>">
    <div class="auth-container container_new" style="background-color: <?php
    if (isset($popup_ui_values->popupBgColor)) {
        echo $popup_ui_values->popupBgColor;
    } else {
        echo "white";
    }
    ?>">
        <!-- Top section with Back button and Help link -->
        <div class="top_icon">
            <a href="<?php echo $loginPageUrl; ?>" class="back-button"
               style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                   echo $popup_ui_values->popupBtnColor;
               } else {
                   echo "#ff8500";
               } ?>">← Back</a>

        </div>

        <!-- Heading and instructions -->
        <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
            echo $popup_ui_values->popupTextColor;
        } else {
            echo "black";
        } ?>">Two-Factor Authentication</h2>
        <p>Choose one of these methods to log in</p>

        <!-- Form for selecting MFA method -->
        <form method="post" action="<?php print_r($formPostUrl); ?>" id="mfa-form">
            <?php echo $formKey; ?>
            <input type="hidden" name="mopostoption" value="method">
            <input type="hidden" name="miniorangetfa_method" id="miniorangetfa_method" value="">

            <!-- Wrapper for all available authentication methods -->
            <div class="auth-methods-wrapper" style="background-color: ; border-radius: 2px;">
                <?php 
                foreach ($activeMethods as $value): 
                ?>
                    <?php if (isset($methods[$value])): ?>
                        <!-- Method card with icon, name, and description -->
                        <div class="auth-method" data-method="<?php echo $value; ?>" onclick="selectMethod(this)">
                            <?php echo $methods[$value]['icon']; ?>
                            <div class="method-info">
                                <p class="method-name"><?php echo htmlspecialchars($methods[$value]['name']); ?></p>
                                <p class="method-desc"><?php echo htmlspecialchars($methods[$value]['desc']); ?></p>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>

            <br>
            <!-- Button to confirm selection -->
            <button class="btn-primary" style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                echo $popup_ui_values->popupBtnColor;
            } else {
                echo "#ff8500";
            } ?>" type="submit">Confirm Selection
            </button>
        </form>

        <!-- Skip for Now Option -->
        <div class="secondary-actions" style="display: flex; margin-top: 3rem;">
            <?php if ($customer_skip_twofa == 1) { ?>
                <?php echo $formKey; ?>
                <div class="skipTwoFa_section">
                    <form method="post" name="skip-twoFA-remind" action="<?php echo $formPostUrl; ?>">
                        <?php echo $formKey; ?>
                        <input type="hidden" name="skiptwofa" value="skip_twofa">
                        <button class="skip_button"
                                style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                                    echo $popup_ui_values->popupBtnColor;
                                } else {
                                    echo "#ff8500";
                                } ?>" type="submit">Remind Me Later
                        </button>
                    </form>
                </div>
            <?php } ?>
        </div>

        <script>
            // Function to handle going back to the previous page
            function goBack() {
                window.history.back();
            }

            // Function to handle method selection by the user
            function selectMethod(element) {
                // Remove 'selected' class from all methods
                var methods = document.querySelectorAll('.auth-method');
                methods.forEach(function (method) {
                    method.classList.remove('selected');
                });

                // Add 'selected' class to the clicked method
                element.classList.add('selected');

                // Set the selected method's value to the hidden input
                var selectedMethod = element.getAttribute('data-method');
                document.getElementById('miniorangetfa_method').value = selectedMethod;
            }

            // Add event listener to ensure a method is selected before form submission
            document.getElementById('mfa-form').addEventListener('submit', function (event) {
                // Get the value of the hidden input that stores the selected method
                var selectedMethod = document.getElementById('miniorangetfa_method').value;

                // If no method is selected, prevent form submission and show an error message
                if (!selectedMethod) {
                    event.preventDefault(); // Prevent form submission
                    alert('Please select a method to proceed.'); // Show error message
                }
            });
        </script>
    </body>
    </html>
    <?php
}


function InvokeUserTFA($formKey, $formPostUrl, $loginPageUrl, $error, $request, $show_kba_button, $popup_ui_values, $is_device_based_enabled, $is_device_limit_exceeded, $otp_length, $adminEmail)
{
    ?>
    <body style="background-size: 100% 100%;background-color: <?php if (isset($popup_ui_values->BgColor)) {
        echo $popup_ui_values->BgColor;
    } else {
        echo "white";
    } ?> ">
    <div class="container_new" style="background-color: <?php
    if (isset($popup_ui_values->popupBgColor)) {
        echo $popup_ui_values->popupBgColor;
    } else {
        echo "white";
    }
    ?>">
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <a href="<?php echo $loginPageUrl; ?>" class="back-button"
               style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                   echo $popup_ui_values->popupBtnColor;
               } else {
                   echo "#ff8500";
               } ?>">← Back</a>
            <a href="mailto:<?php echo $adminEmail; ?>" class="help-dropdown"
               style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                   echo $popup_ui_values->popupBtnColor;
               } else {
                   echo "#ff8500";
               } ?>">Help?</a>
        </div>

        <form method="post" action="<?php echo $formPostUrl; ?>">
            <?php echo $formKey; ?>
            <input type="hidden" name="mopostoption" value="uservalotp">
            <input type="hidden" id="Passcode" name="Passcode">
            <h2 style="font-weight: bold;color: <?php if (isset($popup_ui_values->popupTextColor)) {
                echo $popup_ui_values->popupTextColor;
            } else {
                echo "black";
            } ?>">Two-Factor Authentication</h2>

            <div class="message_container" style="color: <?php echo $error ? '#721c24' : '#155724'; ?>;
                background-color: <?php echo $error ? '#f8d7da' : '#d4edda'; ?>;
                border: 0.1rem solid <?php echo $error ? '#f5c6cb' : '#c3e6cb'; ?>;">
                <?php if (isset($request["message"]) && !$error): ?>
                    <?php echo($request["message"]); ?>
                <?php elseif (isset($request['active_method']) && $request['active_method'] == 'GoogleAuthenticator'): ?>
                    Enter the code from the Google Authenticator app to complete the validation.
                <?php elseif (!$error): ?>
                    Enter OTP sent to
                    <?php echo isset($request['active_method']) ? htmlspecialchars($request['active_method']) : ''; ?>
                <?php elseif ($error): ?>
                    <?php showerrormessage($popup_ui_values); ?>
                <?php endif; ?>
            </div>

            <div class="input-group" id="moPass">
                <?php for ($i = 1; $i <= $otp_length; $i++): ?>
                    <input type="text" maxlength="1" inputmode="numeric"
                           aria-label="Verification Code Digit <?php echo $i; ?>">
                <?php endfor; ?>
            </div>

            <?php if ($is_device_based_enabled && $is_device_limit_exceeded): ?>
                <div style="margin-top: 15px; margin-bottom: 10px;">
                    <input type="checkbox" id="rememberDevice" name="rememberDevice" value="1"
                           style="margin-right: 10px;">
                    <label for="rememberDevice" style="font-weight: normal;">Remember My Device</label>
                </div>
            <?php endif; ?>
            <br>

            <button class="btn-primary" style="background-color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                echo $popup_ui_values->popupBtnColor;
            } else {
                echo "#ff8500";
            } ?>" type="submit">Verify
            </button>

        </form>
        <div class="secondary-actions"
             style="display: flex; margin-top: 20px; align-items: center; justify-content: space-between;">
            <?php if (!isset($request["active_method"]) || $request["active_method"] != 'GoogleAuthenticator'): ?>
                <a href="#" style="color:<?php if (isset($popup_ui_values->popupBtnColor)) {
                    echo $popup_ui_values->popupBtnColor;
                } else {
                    echo "#ff8500";
                } ?>" class="resend-link">Resend
                    Code</a>
            <?php endif; ?>
        </div>

        <?php if ($show_kba_button == 1): ?>
            <br>
            <a href="<?php echo $formPostUrl; ?>/kba?&invoke_kba_validate=invoke_kba_validate">Login with KBA
                Method</a>
        <?php endif; ?>
    </div>

    <script>
        function codeAddress() {
            var redirectElement = document.getElementById("redirect_to");
            if (redirectElement) {
                redirectElement.value = window.location;
            }
        }

        document.addEventListener('DOMContentLoaded', function () {
            const passcodeInputs = document.querySelectorAll('#moPass input[type="text"]');
            const passcodeHiddenInput = document.getElementById('Passcode');

            // Function to update the hidden Passcode field
            function updatePasscode() {
                let passcode = '';
                passcodeInputs.forEach(input => {
                    passcode += input.value.trim(); // Trim any accidental spaces
                });
                passcodeHiddenInput.value = passcode;
            }

            // Add event listeners to all passcode inputs
            passcodeInputs.forEach((input, index) => {
                // On input or paste, update the Passcode field
                input.addEventListener('input', updatePasscode);
                input.addEventListener('paste', (event) => {
                    // Handle paste event
                    event.preventDefault();
                    const pasteData = event.clipboardData.getData('text').trim();
                    const pasteChars = pasteData.split('');

                    for (let i = 0; i < pasteChars.length; i++) {
                        if (index + i < passcodeInputs.length) {
                            passcodeInputs[index + i].value = pasteChars[i];
                        }
                    }

                    updatePasscode();
                });

                // Auto-focus on the next input field when typing
                input.addEventListener('input', () => {
                    if (input.value.length == input.maxLength && index + 1 < passcodeInputs.length) {
                        passcodeInputs[index + 1].focus();
                    }
                });
            });
        });

    </script>
    </body>
    <?php
}


function KBAMethod($formKey, $formPostUrl, $loginPageUrl, $KBAQuestion_set1, $KBAQuestion_set2, $popup_ui_values)
{
    ?>
    <body
        style="--popup-background-color: <?php if (isset($popup_ui_values->popup_ui_background_colour) && $popup_ui_values->popup_ui_background_colour != NULL) {
            print_r($popup_ui_values->popup_ui_background_colour);
        } else {
            print_r("#bbb1b9");
        } ?> ;--background-text-color:<?php if (isset($popup_ui_values->popup_ui_header_colour)) {
            print_r($popup_ui_values->popup_ui_header_colour);
        } ?> ;background-image: url('<?php if (isset($popup_ui_values->popup_ui_background_image)) {
            print_r($popup_ui_values->popup_ui_background_image);
        } ?>') ;  background-size: 100% 100%;">

    <div class="customer_card">
        <div class="card-title">
        </div>
        <br>
        <div class="card-description">
            <form method="post" action="<?php print_r($formPostUrl); ?>">
                <?php print_r($formKey); ?>
                <input type="hidden" name="kba_method_set" value="kba_method_set"/>

                <br>
                <div class="col-sm-8">
                    <select name="q1" class="customer-method-input-box" id="q1"
                            style="--input-background-color: <?php if (isset($popup_ui_values->popup_ui_input_background_color)) {
                                print_r($popup_ui_values->popup_ui_input_background_color);
                            } ?> ; --input-text-color:<?php if (isset($popup_ui_values->popup_ui_input_text_color)) {
                                print_r($popup_ui_values->popup_ui_input_text_color);
                            } ?> ;height:40px;">
                        <?php
                        $Question_set1 = json_decode($KBAQuestion_set1, true);

                        foreach ($Question_set1 as $item) {
                            echo "<option value='$item'>$item</option>";
                        }
                        ?>
                    </select>
                </div>

                <input type="text"
                       style="background: <?php if (isset($popup_ui_values->popup_ui_input_background_color)) {
                           print_r($popup_ui_values->popup_ui_input_background_color);
                       } ?> ; color:<?php if (isset($popup_ui_values->popup_ui_input_text_color)) {
                           print_r($popup_ui_values->popup_ui_input_text_color);
                       } ?> ;" class="method-input-box" name="answer1" value="" required/>
                <br>

                <div class="col-sm-8">
                    <select name="q2" class="customer-method-input-box" id="q2"
                            style="--input-background-color: <?php if (isset($popup_ui_values->popup_ui_input_background_color)) {
                                print_r($popup_ui_values->popup_ui_input_background_color);
                            } ?> ; --input-text-color:<?php if (isset($popup_ui_values->popup_ui_input_text_color)) {
                                print_r($popup_ui_values->popup_ui_input_text_color);
                            } ?> ;height:40px;">
                        <?php
                        $Question_set2 = json_decode($KBAQuestion_set2, true);

                        foreach ($Question_set2 as $item) {
                            echo "<option value='$item'>$item</option>";
                        }
                        ?>
                    </select>
                </div>
                <input type="text"
                       style="background: <?php if (isset($popup_ui_values->popup_ui_input_background_color)) {
                           print_r($popup_ui_values->popup_ui_input_background_color);
                       } ?> ; color:<?php if (isset($popup_ui_values->popup_ui_input_text_color)) {
                           print_r($popup_ui_values->popup_ui_input_text_color);
                       } ?> ;" class="method-input-box" name="answer2" value="" required/>
                <br>
                <table style="width:100%">
                    <tr>
                        <td style="width:35%">
                            <b>Enter your own question:</b>
                        </td>
                        <td>
                            <input type="text"
                                   style="background: <?php if (isset($popup_ui_values->popup_ui_input_background_color)) {
                                       print_r($popup_ui_values->popup_ui_input_background_color);
                                   } ?> ; color:<?php if (isset($popup_ui_values->popup_ui_input_text_color)) {
                                       print_r($popup_ui_values->popup_ui_input_text_color);
                                   } ?> ;" class="method-input-box" name="q3" value="" required/>
                        </td>
                    </tr>
                    <tr>
                        <td style="width:35%">
                            <b>Answer:</b>
                        </td>
                        <td>
                            <input type="text"
                                   style="background: <?php if (isset($popup_ui_values->popup_ui_input_background_color)) {
                                       print_r($popup_ui_values->popup_ui_input_background_color);
                                   } ?> ; color:<?php if (isset($popup_ui_values->popup_ui_input_text_color)) {
                                       print_r($popup_ui_values->popup_ui_input_text_color);
                                   } ?> ;" class="method-input-box" name="answer3" value="" required/>
                        </td>
                    </tr>

                </table>


                <button class="customer_btn"
                        style="--button-color: <?php if (isset($popup_ui_values->popup_ui_button_colour) && $popup_ui_values->popup_ui_button_colour != NULL) {
                            print_r($popup_ui_values->popup_ui_button_colour);
                        } else {
                            print_r("#ff8500");
                        } ?>;--button-text-color:<?php if (isset($popup_ui_values->popup_ui_button_text_color)) {
                            print_r($popup_ui_values->popup_ui_button_text_color);
                        } ?> " type="submit">SAVE
                </button>

            </form>
            <form method="post" action="<?php print_r($formPostUrl); ?>">
                <?php print_r($formKey); ?>
                <button class="customer_btn"
                        style="margin-left: 100px;margin-top:-32px; position: absolute;--button-color: <?php if (isset($popup_ui_values->popup_ui_button_colour) && $popup_ui_values->popup_ui_button_colour != NULL) {
                            print_r($popup_ui_values->popup_ui_button_colour);
                        } else {
                            print_r("#ff8500");
                        } ?>;--button-text-color:<?php if (isset($popup_ui_values->popup_ui_button_text_color)) {
                            print_r($popup_ui_values->popup_ui_button_text_color);
                        } ?> " type="submit" name="skip_kba_config" value="SKIP">SKIP
                </button>
            </form>
        </div>
    </div>
    </body>
    <?php
}

function KBAValidate($formKey, $formPostUrl, $loginPageUrl, $kba_random_questions, $popup_ui_values, $is_device_based_enabled, $is_device_limit_exceeded)
{
    ?>
    <body
        style="--popup-background-color: <?php if (isset($popup_ui_values->popup_ui_background_colour) && $popup_ui_values->popup_ui_background_colour != NULL) {
            print_r($popup_ui_values->popup_ui_background_colour);
        } else {
            print_r("#bbb1b9");
        } ?> ;--background-text-color:<?php if (isset($popup_ui_values->popup_ui_header_colour)) {
            print_r($popup_ui_values->popup_ui_header_colour);
        } ?> ;background-image: url('<?php if (isset($popup_ui_values->popup_ui_background_image)) {
            print_r($popup_ui_values->popup_ui_background_image);
        } ?>') ;  background-size: 100% 100%; ">
    <div class="customer_card">
        <div class="card-title">
        </div>
        <br>
        <div class="card-description">
            <form method="post" action="<?php print_r($formPostUrl); ?>/kba">
                <?php print_r($formKey); ?>
                <input type="hidden" name="q1" value="<?php print_r($kba_random_questions[2]); ?>"/>
                <input type="hidden" name="q2" value="<?php print_r($kba_random_questions[3]); ?>"/>

                <table style="width:100%">
                    <tr>
                        <td style="width:30%;">
                            <b> Question 1: </b></td>
                        <td>
                            <?php print_r($kba_random_questions[0]['question']); ?></td>
                    </tr>
                    <tr>
                        <td style="width:30%;">
                            <b> Answer 1:</b></td>
                        <td><input
                                style="background: <?php if (isset($popup_ui_values->popup_ui_input_background_color)) {
                                    print_r($popup_ui_values->popup_ui_input_background_color);
                                } ?> ; color:<?php if (isset($popup_ui_values->popup_ui_input_text_color)) {
                                    print_r($popup_ui_values->popup_ui_input_text_color);
                                } ?> ;width:100%;float:right" type="text" class="method-input-box" name="answer1"
                                value="" required/></td>
                    </tr>
                    <tr>
                        <td style="width:30%;">
                            <b>Question 2: </b></td>
                        <td><?php print_r($kba_random_questions[1]['question']); ?></td>
                    </tr>
                    <tr>
                        <td style="width:30%;">
                            <b> Answer 2:</b></td>
                        <td><input
                                style="background: <?php if (isset($popup_ui_values->popup_ui_input_background_color)) {
                                    print_r($popup_ui_values->popup_ui_input_background_color);
                                } ?> ; color:<?php if (isset($popup_ui_values->popup_ui_input_text_color)) {
                                    print_r($popup_ui_values->popup_ui_input_text_color);
                                } ?> ;width:100%;float:right" type="text" class="method-input-box" name="answer2"
                                value="" required/></td>
                    </tr>

                </table>

                <br>
                <?php if ($is_device_based_enabled && $is_device_limit_exceeded) { ?>
                    <div class="customer_row" style="margin-top: 15px;margin-botton: 10px;">
                        <div class="col-sm-12">
                            <input type="checkbox" id="rememberDevice" name="rememberDevice" value="1"
                                   style="margin-right: 10px;">
                            <label for="rememberDevice" style="font-weight: normal;">Remember My Device</label>
                        </div>
                    </div>
                <?php } ?>
                <br>

                <button class="customer_btn"
                        style="--button-color: <?php if (isset($popup_ui_values->popup_ui_button_colour) && $popup_ui_values->popup_ui_button_colour != NULL) {
                            print_r($popup_ui_values->popup_ui_button_colour);
                        } else {
                            print_r("#ff8500");
                        } ?>;--button-text-color:<?php if (isset($popup_ui_values->popup_ui_button_text_color)) {
                            print_r($popup_ui_values->popup_ui_button_text_color);
                        } ?> " type="submit">Login
                </button>
            </form>
            <form method="post" action="<?php print_r($loginPageUrl); ?>">
                <button class="customer_btn" type="submit"
                        style="--button-color: <?php if (isset($popup_ui_values->popup_ui_button_colour) && $popup_ui_values->popup_ui_button_colour != NULL) {
                            print_r($popup_ui_values->popup_ui_button_colour);
                        } else {
                            print_r("#ff8500");
                        } ?>;--button-text-color:<?php if (isset($popup_ui_values->popup_ui_button_text_color)) {
                            print_r($popup_ui_values->popup_ui_button_text_color);
                        } ?> ;margin-top:-32px;margin-left:150px;position:absolute;">Cancel
                </button>
            </form>

        </div>
    </div>

    <?php

    }

function showerrormessage($popup_ui_values)
    { ?>

        <div class="error_message"
             style="--error-message-text: <?php if (isset($popup_ui_values->popup_ui_error_text_color) && $popup_ui_values->popup_ui_error_text_color != NULL) {
                 print_r($popup_ui_values->popup_ui_error_text_color);
             } else {
                 print_r("#fa0202");
             } ?>">
            <center>Please Enter Correct OTP
                <center>
        </div>

<?php }

function countrycode($popup_ui_values)
    {
        ?>
        <!-- All countries -->
        <select id="phone" name="countrycode" class="customer-method-input-box"
                style="--input-background-color: <?php if (isset($popup_ui_values->popup_ui_input_background_color)) {
                    print_r($popup_ui_values->popup_ui_input_background_color);
                } ?>
                    ; --input-text-color:<?php if (isset($popup_ui_values->popup_ui_input_text_color)) {
                    print_r($popup_ui_values->popup_ui_input_text_color);
                } ?>
                    ;width:40%;height:100% ">

            <option value="93">Afghanistan +93</option>
            <option value="358">Aland Islands +358</option>
            <option value="355">Albania +355</option>
            <option value="213">Algeria +213</option>
            <option value="1684">American Samoa +1684</option>
            <option value="376">Andorra +376</option>
            <option value="244">Angola +244</option>
            <option value="1264">Anguilla +1264</option>
            <option value="672">Antarctica +672</option>
            <option value="1268">Antigua and Barbuda +1268</option>
            <option value="54">Argentina +54</option>
            <option value="374">Armenia +374</option>
            <option value="297">Aruba +297</option>
            <option value="61">Australia +61</option>
            <option value="43">Austria +43</option>
            <option value="994">Azerbaijan +994</option>
            <option value="1242">Bahamas +1242</option>
            <option value="973">Bahrain +973</option>
            <option value="880">Bangladesh +880</option>
            <option value="1246">Barbados +1246</option>
            <option value="375">Belarus +375</option>
            <option value="32">Belgium +32</option>
            <option value="501">Belize +501</option>
            <option value="229">Benin +229</option>
            <option value="1441">Bermuda +1441</option>
            <option value="975">Bhutan +975</option>
            <option value="591">Bolivia +591</option>
            <option value="599">Bonaire, Sint Eustatius and Saba +599</option>
            <option value="387">Bosnia and Herzegovina +387</option>
            <option value="267">Botswana +267</option>
            <option value="55">Bouvet Island +55</option>
            <option value="55">Brazil +55</option>
            <option value="246">British Indian Ocean Territory +246</option>
            <option value="673">Brunei Darussalam +673</option>
            <option value="359">Bulgaria +359</option>
            <option value="226">Burkina Faso +226</option>
            <option value="257">Burundi +257</option>
            <option value="855">Cambodia +855</option>
            <option value="237">Cameroon +237</option>
            <option value="1">Canada +1</option>
            <option value="238">Cape Verde +238</option>
            <option value="1345">Cayman Islands +1345</option>
            <option value="236">Central African Republic +236</option>
            <option value="235">Chad +235</option>
            <option value="56">Chile +56</option>
            <option value="86">China +86</option>
            <option value="61">Christmas Island +61</option>
            <option value="672">Cocos (Keeling) Islands +672</option>
            <option value="57">Colombia +57</option>
            <option value="269">Comoros +269</option>
            <option value="242">Congo +242</option>
            <option value="242">Congo, Democratic Republic of the Congo +242</option>
            <option value="682">Cook Islands +682</option>
            <option value="506">Costa Rica +506</option>
            <option value="225">Cote D'Ivoire +225</option>
            <option value="385">Croatia +385</option>
            <option value="53">Cuba +53</option>
            <option value="599">Curacao +599</option>
            <option value="357">Cyprus +357</option>
            <option value="420">Czech Republic +420</option>
            <option value="45">Denmark +45</option>
            <option value="253">Djibouti +253</option>
            <option value="1767">Dominica +1767</option>
            <option value="1809">Dominican Republic +1809</option>
            <option value="593">Ecuador +593</option>
            <option value="20">Egypt +20</option>
            <option value="503">El Salvador +503</option>
            <option value="240">Equatorial Guinea +240</option>
            <option value="291">Eritrea +291</option>
            <option value="372">Estonia +372</option>
            <option value="251">Ethiopia +251</option>
            <option value="500">Falkland Islands (Malvinas) +500</option>
            <option value="298">Faroe Islands +298</option>
            <option value="679">Fiji +679</option>
            <option value="358">Finland +358</option>
            <option value="33">France +33</option>
            <option value="594">French Guiana +594</option>
            <option value="689">French Polynesia +689</option>
            <option value="262">French Southern Territories +262</option>
            <option value="241">Gabon +241</option>
            <option value="220">Gambia +220</option>
            <option value="995">Georgia +995</option>
            <option value="49">Germany +49</option>
            <option value="233">Ghana +233</option>
            <option value="350">Gibraltar +350</option>
            <option value="30">Greece +30</option>
            <option value="299">Greenland +299</option>
            <option value="1473">Grenada +1473</option>
            <option value="590">Guadeloupe +590</option>
            <option value="1671">Guam +1671</option>
            <option value="502">Guatemala +502</option>
            <option value="44">Guernsey +44</option>
            <option value="224">Guinea +224</option>
            <option value="245">Guinea-Bissau +245</option>
            <option value="592">Guyana +592</option>
            <option value="509">Haiti +509</option>
            <option value="0">Heard Island and Mcdonald Islands +0</option>
            <option value="39">Holy See (Vatican City State) +39</option>
            <option value="504">Honduras +504</option>
            <option value="852">Hong Kong +852</option>
            <option value="36">Hungary +36</option>
            <option value="354">Iceland +354</option>
            <option value="91" selected>India +91</option>
            <option value="62">Indonesia +62</option>
            <option value="98">Iran, Islamic Republic of +98</option>
            <option value="964">Iraq +964</option>
            <option value="353">Ireland +353</option>
            <option value="44">Isle of Man +44</option>
            <option value="972">Israel +972</option>
            <option value="39">Italy +39</option>
            <option value="1876">Jamaica +1876</option>
            <option value="81">Japan +81</option>
            <option value="44">Jersey +44</option>
            <option value="962">Jordan +962</option>
            <option value="7">Kazakhstan +7</option>
            <option value="254">Kenya +254</option>
            <option value="686">Kiribati +686</option>
            <option value="850">Korea, Democratic People's Republic of +850</option>
            <option value="82">Korea, Republic of +82</option>
            <option value="381">Kosovo +381</option>
            <option value="965">Kuwait +965</option>
            <option value="996">Kyrgyzstan +996</option>
            <option value="856">Lao People's Democratic Republic +856</option>
            <option value="371">Latvia +371</option>
            <option value="961">Lebanon +961</option>
            <option value="266">Lesotho +266</option>
            <option value="231">Liberia +231</option>
            <option value="218">Libyan Arab Jamahiriya +218</option>
            <option value="423">Liechtenstein +423</option>
            <option value="370">Lithuania +370</option>
            <option value="352">Luxembourg +352</option>
            <option value="853">Macao +853</option>
            <option value="389">Macedonia, the Former Yugoslav Republic of +389</option>
            <option value="261">Madagascar +261</option>
            <option value="265">Malawi +265</option>
            <option value="60">Malaysia +60</option>
            <option value="960">Maldives +960</option>
            <option value="223">Mali +223</option>
            <option value="356">Malta +356</option>
            <option value="692">Marshall Islands +692</option>
            <option value="596">Martinique +596</option>
            <option value="222">Mauritania +222</option>
            <option value="230">Mauritius +230</option>
            <option value="262">Mayotte +262</option>
            <option value="52">Mexico +52</option>
            <option value="691">Micronesia, Federated States of +691</option>
            <option value="373">Moldova, Republic of +373</option>
            <option value="377">Monaco +377</option>
            <option value="976">Mongolia +976</option>
            <option value="382">Montenegro +382</option>
            <option value="1664">Montserrat +1664</option>
            <option value="212">Morocco +212</option>
            <option value="258">Mozambique +258</option>
            <option value="95">Myanmar +95</option>
            <option value="264">Namibia +264</option>
            <option value="674">Nauru +674</option>
            <option value="977">Nepal +977</option>
            <option value="31">Netherlands +31</option>
            <option value="599">Netherlands Antilles +599</option>
            <option value="687">New Caledonia +687</option>
            <option value="64">New Zealand +64</option>
            <option value="505">Nicaragua +505</option>
            <option value="227">Niger +227</option>
            <option value="234">Nigeria +234</option>
            <option value="683">Niue +683</option>
            <option value="672">Norfolk Island +672</option>
            <option value="1670">Northern Mariana Islands +1670</option>
            <option value="47">Norway +47</option>
            <option value="968">Oman +968</option>
            <option value="92">Pakistan +92</option>
            <option value="680">Palau +680</option>
            <option value="970">Palestinian Territory, Occupied +970</option>
            <option value="507">Panama +507</option>
            <option value="675">Papua New Guinea +675</option>
            <option value="595">Paraguay +595</option>
            <option value="51">Peru +51</option>
            <option value="63">Philippines +63</option>
            <option value="64">Pitcairn +64</option>
            <option value="48">Poland +48</option>
            <option value="351">Portugal +351</option>
            <option value="1787">Puerto Rico +1787</option>
            <option value="974">Qatar +974</option>
            <option value="262">Reunion +262</option>
            <option value="40">Romania +40</option>
            <option value="70">Russian Federation +70</option>
            <option value="250">Rwanda +250</option>
            <option value="590">Saint Barthelemy +590</option>
            <option value="290">Saint Helena +290</option>
            <option value="1869">Saint Kitts and Nevis +1869</option>
            <option value="1758">Saint Lucia +1758</option>
            <option value="590">Saint Martin +590</option>
            <option value="508">Saint Pierre and Miquelon +508</option>
            <option value="1784">Saint Vincent and the Grenadines +1784</option>
            <option value="684">Samoa +684</option>
            <option value="378">San Marino +378</option>
            <option value="239">Sao Tome and Principe +239</option>
            <option value="966">Saudi Arabia +966</option>
            <option value="221">Senegal +221</option>
            <option value="381">Serbia +381</option>
            <option value="381">Serbia and Montenegro +381</option>
            <option value="248">Seychelles +248</option>
            <option value="232">Sierra Leone +232</option>
            <option value="65">Singapore +65</option>
            <option value="1">Sint Maarten +1</option>
            <option value="421">Slovakia +421</option>
            <option value="386">Slovenia +386</option>
            <option value="677">Solomon Islands +677</option>
            <option value="252">Somalia +252</option>
            <option value="27">South Africa +27</option>
            <option value="500">South Georgia and the South Sandwich Islands +500</option>
            <option value="211">South Sudan +211</option>
            <option value="34">Spain +34</option>
            <option value="94">Sri Lanka +94</option>
            <option value="249">Sudan +249</option>
            <option value="597">Suriname +597</option>
            <option value="47">Svalbard and Jan Mayen +47</option>
            <option value="268">Swaziland +268</option>
            <option value="46">Sweden +46</option>
            <option value="41">Switzerland +41</option>
            <option value="963">Syrian Arab Republic +963</option>
            <option value="886">Taiwan, Province of China +886</option>
            <option value="992">Tajikistan +992</option>
            <option value="255">Tanzania, United Republic of +255</option>
            <option value="66">Thailand +66</option>
            <option value="670">Timor-Leste +670</option>
            <option value="228">Togo +228</option>
            <option value="690">Tokelau +690</option>
            <option value="676">Tonga +676</option>
            <option value="1868">Trinidad and Tobago +1868</option>
            <option value="216">Tunisia +216</option>
            <option value="90">Turkey +90</option>
            <option value="7370">Turkmenistan +7370</option>
            <option value="1649">Turks and Caicos Islands +1649</option>
            <option value="688">Tuvalu +688</option>
            <option value="256">Uganda +256</option>
            <option value="380">Ukraine +380</option>
            <option value="971">United Arab Emirates +971</option>
            <option value="44">United Kingdom +44</option>
            <option value="1">United States +1</option>
            <option value="1">United States Minor Outlying Islands +1</option>
            <option value="598">Uruguay +598</option>
            <option value="998">Uzbekistan +998</option>
            <option value="678">Vanuatu +678</option>
            <option value="58">Venezuela +58</option>
            <option value="84">Viet Nam +84</option>
            <option value="1284">Virgin Islands, British +1284</option>
            <option value="1340">Virgin Islands, U.s. +1340</option>
            <option value="681">Wallis and Futuna +681</option>
            <option value="212">Western Sahara +212</option>
            <option value="967">Yemen +967</option>
            <option value="260">Zambia +260</option>
            <option value="263">Zimbabwe +263</option>
        </select>
<?php } ?>

<script>

        // updated one


        document.addEventListener('DOMContentLoaded', function () {
            const resendOtpButton = document.querySelector('.resend-link');
            const loader = document.createElement('div'); // Create a loader element
            loader.className = 'loader'; // You can customize the loader with CSS
            loader.style.display = 'none'; // Initially hidden

            // Add the loader to the body or a specific container
            document.body.appendChild(loader);

            if (resendOtpButton) {

                resendOtpButton.addEventListener('click', function (event) {
                    event.preventDefault();

                    // Get URL parameters
                    const urlParams = new URLSearchParams(window.location.search);

                    // Initialize variables
                    let activeMethod = '';
                    let username = '<?php echo $email; ?>'; // This will store email or phone number
                    let phone = ''; // Phone number including country code
                    const countryCode = urlParams.get('countrycode') || ''; // Get country code

                    // Edge Case 1: OOS Method (Step: OOSMethodValidation)
                    if (urlParams.get('step') === 'OOSMethodValidation') {
                        activeMethod = 'OOS';
                        phone = '+' + countryCode + urlParams.get('phone'); // Phone number with country code
                    }
                    // Edge Case 2: OOSE Method (Step: OOSEMethodValidation)
                    else if (urlParams.get('step') === 'OOSEMethodValidation') {
                        activeMethod = 'OOSE';
                        phone = '+' + countryCode + urlParams.get('phone'); // Phone number with country code
                    }
                    // Edge Case 3: OOE Method (Step: OOEMethodValidation)
                    else if (urlParams.get('step') === 'OOEMethodValidation') {
                        activeMethod = 'OOE';
                        phone = ''; // No phone in this case
                    }
                    // Edge Case 4: OTP Sent to Email (InvokeTFA case)
                    else {
                        // Try to get the active method from URL parameters or determine it from the context
                        activeMethod = urlParams.get('active_method') || '';
                        
                        // If no active_method in URL, try to determine from the context
                        if (!activeMethod) {
                            // Check if we're in a specific step that indicates the method
                            const step = urlParams.get('step');
                            if (step === 'OOSMethodValidation') {
                                activeMethod = 'OOS';
                            } else if (step === 'OOEMethodValidation') {
                                activeMethod = 'OOE';
                            } else if (step === 'OOSEMethodValidation') {
                                activeMethod = 'OOSE';
                            } else {
                                // Default to OOE for email-based OTP if no other method is specified
                                activeMethod = 'OOE';
                            }
                        }
                        
                        phone = ''; // No phone in this case

                        // Function to clean up the URL for the "else" case
                        function cleanUrl() {
                            const currentUrl = new URL(window.location.href);

                            // Extract the pathname and remove any unwanted "message/" segment
                            let cleanedPathname = currentUrl.pathname.replace(/message\/[^\/]+\/$/, '');

                            // Update the URL with the cleaned pathname and keep the query parameters intact
                            currentUrl.pathname = cleanedPathname;

                            // Update the browser's URL without reloading the page
                            window.history.pushState({}, '', currentUrl);
                        }

                        // Clean the URL on page load
                        cleanUrl();
                    }

                    // Default case for sending OTP
                    const requestData = {
                        username: username, // Will be email or phone number depending on the case
                        authType: activeMethod, // Active method based on the case
                        phone: phone // Phone number with country code (if applicable)
                    };

                    // console.log(requestData, "-------");
                    const apiUrl = '<?php echo $this->getBaseUrl(); ?>rest/V1/mo2fa/headless/sendOtpApi';

                    resendOtpButton.disabled = true;

                    fetch(apiUrl, {
                        method: 'POST',
                        headers: {'Content-Type': 'application/json'},
                        body: JSON.stringify(requestData)
                    })
                        .then(response => {
                            // Check if the response is JSON
                            const contentType = response.headers.get('content-type');
                            if (contentType && contentType.includes('application/json')) {
                                return response.json();
                            } else {
                                throw new Error('Invalid response format: Expected JSON');
                            }
                        })
                        .then(data => {
                            // Check if `data` is an array and has at least one element
                            if (Array.isArray(data) && data.length > 0) {
                                const responseData = data[0]; // Access the first object in the array
                                console.log(responseData);
                                // alert(responseData.status);
                                // Check the status and update the URL with the appropriate message
                                let newMessage = '';
                                if (responseData.status === "SUCCESS") {
                                    newMessage = 'OTP has been resend successfully!';
                                } else {
                                    newMessage = responseData.message;
                                }

                                // Update the URL by removing the `error` parameter (if present) and adding/updating the `message` parameter
                                const currentUrl = new URL(window.location.href);

                                // Conditionally remove the `error` parameter only if it exists
                                if (currentUrl.searchParams.has('error')) {
                                    currentUrl.searchParams.delete('error'); // Remove the `error` parameter
                                }

                                currentUrl.searchParams.set('message', newMessage); // Update the `message` parameter
                                
                                // Ensure the active_method is preserved in the URL for proper OTP length determination
                                if (activeMethod && !currentUrl.searchParams.has('active_method')) {
                                    currentUrl.searchParams.set('active_method', activeMethod);
                                }

                                // Update the URL without reloading the page
                                window.history.pushState({}, '', currentUrl);

                                // Refresh the page to display the updated message
                                window.location.reload();
                            } else {
                                alert('Invalid response format from the server.');
                            }
                        })
                        .catch(error => {
                            console.error('Error:', error);
                            alert('An error occurred: ' + error.message);
                        })
                        .finally(() => {
                            resendOtpButton.textContent = 'Resend Code';
                            resendOtpButton.disabled = false;

                            // Hide the loader after the process is done
                            loader.style.display = 'none';
                        });
                });
            }
        });

        document.addEventListener('DOMContentLoaded', function () {
            const passcodeInputs = document.querySelectorAll('#moPass input[type="text"]');
            const passcodeHiddenInput = document.getElementById('Passcode');

            // Function to update the hidden Passcode field
            function updatePasscode() {
                let passcode = '';
                passcodeInputs.forEach(input => {
                    passcode += input.value.trim(); // Trim any accidental spaces
                });
                passcodeHiddenInput.value = passcode;
            }

            // Add event listeners to all passcode inputs
            passcodeInputs.forEach((input, index) => {
                input.addEventListener('input', () => {
                    updatePasscode();

                    // Auto-focus on the next input field when typing
                    if (input.value.length === input.maxLength && index + 1 < passcodeInputs.length) {
                        passcodeInputs[index + 1].focus();
                    }
                });

                input.addEventListener('paste', (event) => {
                    event.preventDefault();
                    const pasteData = event.clipboardData.getData('text').trim();
                    const pasteChars = pasteData.split('');

                    for (let i = 0; i < pasteChars.length; i++) {
                        if (index + i < passcodeInputs.length) {
                            passcodeInputs[index + i].value = pasteChars[i];
                        }
                    }

                    updatePasscode();
                });

                // Handle Backspace key to move focus backward
                input.addEventListener('keydown', (event) => {
                    if (event.key === 'Backspace' && input.value === '' && index > 0) {
                        passcodeInputs[index - 1].focus();
                    }
                });

                // Handle arrow key navigation between inputs
                input.addEventListener('keydown', (event) => {
                    if (event.key === 'ArrowLeft' && index > 0) {
                        passcodeInputs[index - 1].focus();
                    } else if (event.key === 'ArrowRight' && index + 1 < passcodeInputs.length) {
                        passcodeInputs[index + 1].focus();
                    }
                });
            });
        });

     
</script>
<?php

